// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "pi_modelparameters.hxx"

namespace fews
{
  namespace PI
  {
    // ModelParametersComplexType
    // 

    const ModelParametersComplexType::ModifierTypeSequence& ModelParametersComplexType::
    getModifierType () const
    {
      return this->modifierType_;
    }

    ModelParametersComplexType::ModifierTypeSequence& ModelParametersComplexType::
    getModifierType ()
    {
      return this->modifierType_;
    }

    void ModelParametersComplexType::
    setModifierType (const ModifierTypeSequence& s)
    {
      this->modifierType_ = s;
    }

    const ModelParametersComplexType::GroupSequence& ModelParametersComplexType::
    getGroup () const
    {
      return this->group_;
    }

    ModelParametersComplexType::GroupSequence& ModelParametersComplexType::
    getGroup ()
    {
      return this->group_;
    }

    void ModelParametersComplexType::
    setGroup (const GroupSequence& s)
    {
      this->group_ = s;
    }

    const ModelParametersComplexType::VersionType& ModelParametersComplexType::
    getVersion () const
    {
      return this->version_.get ();
    }

    const ModelParametersComplexType::VersionType& ModelParametersComplexType::
    getVersionDefaultValue ()
    {
      return version_default_value_;
    }


    // ModelParameterGroupComplexType
    // 

    const ModelParameterGroupComplexType::DescriptionOptional& ModelParameterGroupComplexType::
    getDescription () const
    {
      return this->description_;
    }

    ModelParameterGroupComplexType::DescriptionOptional& ModelParameterGroupComplexType::
    getDescription ()
    {
      return this->description_;
    }

    void ModelParameterGroupComplexType::
    setDescription (const DescriptionType& x)
    {
      this->description_.set (x);
    }

    void ModelParameterGroupComplexType::
    setDescription (const DescriptionOptional& x)
    {
      this->description_ = x;
    }

    void ModelParameterGroupComplexType::
    setDescription (::std::auto_ptr< DescriptionType > x)
    {
      this->description_.set (x);
    }

    const ModelParameterGroupComplexType::LocationIdOptional& ModelParameterGroupComplexType::
    getLocationId () const
    {
      return this->locationId_;
    }

    ModelParameterGroupComplexType::LocationIdOptional& ModelParameterGroupComplexType::
    getLocationId ()
    {
      return this->locationId_;
    }

    void ModelParameterGroupComplexType::
    setLocationId (const LocationIdType& x)
    {
      this->locationId_.set (x);
    }

    void ModelParameterGroupComplexType::
    setLocationId (const LocationIdOptional& x)
    {
      this->locationId_ = x;
    }

    void ModelParameterGroupComplexType::
    setLocationId (::std::auto_ptr< LocationIdType > x)
    {
      this->locationId_.set (x);
    }

    const ModelParameterGroupComplexType::ModelOptional& ModelParameterGroupComplexType::
    getModel () const
    {
      return this->model_;
    }

    ModelParameterGroupComplexType::ModelOptional& ModelParameterGroupComplexType::
    getModel ()
    {
      return this->model_;
    }

    void ModelParameterGroupComplexType::
    setModel (const ModelType& x)
    {
      this->model_.set (x);
    }

    void ModelParameterGroupComplexType::
    setModel (const ModelOptional& x)
    {
      this->model_ = x;
    }

    void ModelParameterGroupComplexType::
    setModel (::std::auto_ptr< ModelType > x)
    {
      this->model_.set (x);
    }

    const ModelParameterGroupComplexType::ValidPeriodOptional& ModelParameterGroupComplexType::
    getValidPeriod () const
    {
      return this->validPeriod_;
    }

    ModelParameterGroupComplexType::ValidPeriodOptional& ModelParameterGroupComplexType::
    getValidPeriod ()
    {
      return this->validPeriod_;
    }

    void ModelParameterGroupComplexType::
    setValidPeriod (const ValidPeriodType& x)
    {
      this->validPeriod_.set (x);
    }

    void ModelParameterGroupComplexType::
    setValidPeriod (const ValidPeriodOptional& x)
    {
      this->validPeriod_ = x;
    }

    void ModelParameterGroupComplexType::
    setValidPeriod (::std::auto_ptr< ValidPeriodType > x)
    {
      this->validPeriod_.set (x);
    }

    const ModelParameterGroupComplexType::ParameterSequence& ModelParameterGroupComplexType::
    getParameter () const
    {
      return this->parameter_;
    }

    ModelParameterGroupComplexType::ParameterSequence& ModelParameterGroupComplexType::
    getParameter ()
    {
      return this->parameter_;
    }

    void ModelParameterGroupComplexType::
    setParameter (const ParameterSequence& s)
    {
      this->parameter_ = s;
    }

    const ModelParameterGroupComplexType::EnsembleSequence& ModelParameterGroupComplexType::
    getEnsemble () const
    {
      return this->ensemble_;
    }

    ModelParameterGroupComplexType::EnsembleSequence& ModelParameterGroupComplexType::
    getEnsemble ()
    {
      return this->ensemble_;
    }

    void ModelParameterGroupComplexType::
    setEnsemble (const EnsembleSequence& s)
    {
      this->ensemble_ = s;
    }

    const ModelParameterGroupComplexType::IdType& ModelParameterGroupComplexType::
    getId () const
    {
      return this->id_.get ();
    }

    ModelParameterGroupComplexType::IdType& ModelParameterGroupComplexType::
    getId ()
    {
      return this->id_.get ();
    }

    void ModelParameterGroupComplexType::
    setId (const IdType& x)
    {
      this->id_.set (x);
    }

    void ModelParameterGroupComplexType::
    setId (::std::auto_ptr< IdType > x)
    {
      this->id_.set (x);
    }

    const ModelParameterGroupComplexType::NameOptional& ModelParameterGroupComplexType::
    getName () const
    {
      return this->name_;
    }

    ModelParameterGroupComplexType::NameOptional& ModelParameterGroupComplexType::
    getName ()
    {
      return this->name_;
    }

    void ModelParameterGroupComplexType::
    setName (const NameType& x)
    {
      this->name_.set (x);
    }

    void ModelParameterGroupComplexType::
    setName (const NameOptional& x)
    {
      this->name_ = x;
    }

    void ModelParameterGroupComplexType::
    setName (::std::auto_ptr< NameType > x)
    {
      this->name_.set (x);
    }

    const ModelParameterGroupComplexType::ReadonlyType& ModelParameterGroupComplexType::
    getReadonly () const
    {
      return this->readonly_.get ();
    }

    ModelParameterGroupComplexType::ReadonlyType& ModelParameterGroupComplexType::
    getReadonly ()
    {
      return this->readonly_.get ();
    }

    void ModelParameterGroupComplexType::
    setReadonly (const ReadonlyType& x)
    {
      this->readonly_.set (x);
    }

    ModelParameterGroupComplexType::ReadonlyType ModelParameterGroupComplexType::
    getReadonlyDefaultValue ()
    {
      return ReadonlyType (false);
    }

    const ModelParameterGroupComplexType::ModifiedType& ModelParameterGroupComplexType::
    getModified () const
    {
      return this->modified_.get ();
    }

    ModelParameterGroupComplexType::ModifiedType& ModelParameterGroupComplexType::
    getModified ()
    {
      return this->modified_.get ();
    }

    void ModelParameterGroupComplexType::
    setModified (const ModifiedType& x)
    {
      this->modified_.set (x);
    }

    ModelParameterGroupComplexType::ModifiedType ModelParameterGroupComplexType::
    getModifiedDefaultValue ()
    {
      return ModifiedType (false);
    }


    // ModelParameterComplexType
    // 

    const ModelParameterComplexType::DescriptionOptional& ModelParameterComplexType::
    getDescription () const
    {
      return this->description_;
    }

    ModelParameterComplexType::DescriptionOptional& ModelParameterComplexType::
    getDescription ()
    {
      return this->description_;
    }

    void ModelParameterComplexType::
    setDescription (const DescriptionType& x)
    {
      this->description_.set (x);
    }

    void ModelParameterComplexType::
    setDescription (const DescriptionOptional& x)
    {
      this->description_ = x;
    }

    void ModelParameterComplexType::
    setDescription (::std::auto_ptr< DescriptionType > x)
    {
      this->description_.set (x);
    }

    const ModelParameterComplexType::DblValueOptional& ModelParameterComplexType::
    getDblValue () const
    {
      return this->dblValue_;
    }

    ModelParameterComplexType::DblValueOptional& ModelParameterComplexType::
    getDblValue ()
    {
      return this->dblValue_;
    }

    void ModelParameterComplexType::
    setDblValue (const DblValueType& x)
    {
      this->dblValue_.set (x);
    }

    void ModelParameterComplexType::
    setDblValue (const DblValueOptional& x)
    {
      this->dblValue_ = x;
    }

    void ModelParameterComplexType::
    setDblValue (::std::auto_ptr< DblValueType > x)
    {
      this->dblValue_.set (x);
    }

    const ModelParameterComplexType::IntValueOptional& ModelParameterComplexType::
    getIntValue () const
    {
      return this->intValue_;
    }

    ModelParameterComplexType::IntValueOptional& ModelParameterComplexType::
    getIntValue ()
    {
      return this->intValue_;
    }

    void ModelParameterComplexType::
    setIntValue (const IntValueType& x)
    {
      this->intValue_.set (x);
    }

    void ModelParameterComplexType::
    setIntValue (const IntValueOptional& x)
    {
      this->intValue_ = x;
    }

    void ModelParameterComplexType::
    setIntValue (::std::auto_ptr< IntValueType > x)
    {
      this->intValue_.set (x);
    }

    const ModelParameterComplexType::BoolValueOptional& ModelParameterComplexType::
    getBoolValue () const
    {
      return this->boolValue_;
    }

    ModelParameterComplexType::BoolValueOptional& ModelParameterComplexType::
    getBoolValue ()
    {
      return this->boolValue_;
    }

    void ModelParameterComplexType::
    setBoolValue (const BoolValueType& x)
    {
      this->boolValue_.set (x);
    }

    void ModelParameterComplexType::
    setBoolValue (const BoolValueOptional& x)
    {
      this->boolValue_ = x;
    }

    void ModelParameterComplexType::
    setBoolValue (::std::auto_ptr< BoolValueType > x)
    {
      this->boolValue_.set (x);
    }

    const ModelParameterComplexType::StringValueOptional& ModelParameterComplexType::
    getStringValue () const
    {
      return this->stringValue_;
    }

    ModelParameterComplexType::StringValueOptional& ModelParameterComplexType::
    getStringValue ()
    {
      return this->stringValue_;
    }

    void ModelParameterComplexType::
    setStringValue (const StringValueType& x)
    {
      this->stringValue_.set (x);
    }

    void ModelParameterComplexType::
    setStringValue (const StringValueOptional& x)
    {
      this->stringValue_ = x;
    }

    void ModelParameterComplexType::
    setStringValue (::std::auto_ptr< StringValueType > x)
    {
      this->stringValue_.set (x);
    }

    const ModelParameterComplexType::DateTimeValueOptional& ModelParameterComplexType::
    getDateTimeValue () const
    {
      return this->dateTimeValue_;
    }

    ModelParameterComplexType::DateTimeValueOptional& ModelParameterComplexType::
    getDateTimeValue ()
    {
      return this->dateTimeValue_;
    }

    void ModelParameterComplexType::
    setDateTimeValue (const DateTimeValueType& x)
    {
      this->dateTimeValue_.set (x);
    }

    void ModelParameterComplexType::
    setDateTimeValue (const DateTimeValueOptional& x)
    {
      this->dateTimeValue_ = x;
    }

    void ModelParameterComplexType::
    setDateTimeValue (::std::auto_ptr< DateTimeValueType > x)
    {
      this->dateTimeValue_.set (x);
    }

    const ModelParameterComplexType::TableOptional& ModelParameterComplexType::
    getTable () const
    {
      return this->table_;
    }

    ModelParameterComplexType::TableOptional& ModelParameterComplexType::
    getTable ()
    {
      return this->table_;
    }

    void ModelParameterComplexType::
    setTable (const TableType& x)
    {
      this->table_.set (x);
    }

    void ModelParameterComplexType::
    setTable (const TableOptional& x)
    {
      this->table_ = x;
    }

    void ModelParameterComplexType::
    setTable (::std::auto_ptr< TableType > x)
    {
      this->table_.set (x);
    }

    const ModelParameterComplexType::IdType& ModelParameterComplexType::
    getId () const
    {
      return this->id_.get ();
    }

    ModelParameterComplexType::IdType& ModelParameterComplexType::
    getId ()
    {
      return this->id_.get ();
    }

    void ModelParameterComplexType::
    setId (const IdType& x)
    {
      this->id_.set (x);
    }

    void ModelParameterComplexType::
    setId (::std::auto_ptr< IdType > x)
    {
      this->id_.set (x);
    }

    const ModelParameterComplexType::NameOptional& ModelParameterComplexType::
    getName () const
    {
      return this->name_;
    }

    ModelParameterComplexType::NameOptional& ModelParameterComplexType::
    getName ()
    {
      return this->name_;
    }

    void ModelParameterComplexType::
    setName (const NameType& x)
    {
      this->name_.set (x);
    }

    void ModelParameterComplexType::
    setName (const NameOptional& x)
    {
      this->name_ = x;
    }

    void ModelParameterComplexType::
    setName (::std::auto_ptr< NameType > x)
    {
      this->name_.set (x);
    }


    // EnsembleComplexType
    // 

    const EnsembleComplexType::EnsembleMemberOptional& EnsembleComplexType::
    getEnsembleMember () const
    {
      return this->ensembleMember_;
    }

    EnsembleComplexType::EnsembleMemberOptional& EnsembleComplexType::
    getEnsembleMember ()
    {
      return this->ensembleMember_;
    }

    void EnsembleComplexType::
    setEnsembleMember (const EnsembleMemberType& x)
    {
      this->ensembleMember_.set (x);
    }

    void EnsembleComplexType::
    setEnsembleMember (const EnsembleMemberOptional& x)
    {
      this->ensembleMember_ = x;
    }

    void EnsembleComplexType::
    setEnsembleMember (::std::auto_ptr< EnsembleMemberType > x)
    {
      this->ensembleMember_.set (x);
    }

    const EnsembleComplexType::EnsembleMemberRangeOptional& EnsembleComplexType::
    getEnsembleMemberRange () const
    {
      return this->ensembleMemberRange_;
    }

    EnsembleComplexType::EnsembleMemberRangeOptional& EnsembleComplexType::
    getEnsembleMemberRange ()
    {
      return this->ensembleMemberRange_;
    }

    void EnsembleComplexType::
    setEnsembleMemberRange (const EnsembleMemberRangeType& x)
    {
      this->ensembleMemberRange_.set (x);
    }

    void EnsembleComplexType::
    setEnsembleMemberRange (const EnsembleMemberRangeOptional& x)
    {
      this->ensembleMemberRange_ = x;
    }

    void EnsembleComplexType::
    setEnsembleMemberRange (::std::auto_ptr< EnsembleMemberRangeType > x)
    {
      this->ensembleMemberRange_.set (x);
    }

    const EnsembleComplexType::ParameterSequence& EnsembleComplexType::
    getParameter () const
    {
      return this->parameter_;
    }

    EnsembleComplexType::ParameterSequence& EnsembleComplexType::
    getParameter ()
    {
      return this->parameter_;
    }

    void EnsembleComplexType::
    setParameter (const ParameterSequence& s)
    {
      this->parameter_ = s;
    }

    const EnsembleComplexType::IdType& EnsembleComplexType::
    getId () const
    {
      return this->id_.get ();
    }

    EnsembleComplexType::IdType& EnsembleComplexType::
    getId ()
    {
      return this->id_.get ();
    }

    void EnsembleComplexType::
    setId (const IdType& x)
    {
      this->id_.set (x);
    }

    void EnsembleComplexType::
    setId (::std::auto_ptr< IdType > x)
    {
      this->id_.set (x);
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace fews
{
  namespace PI
  {
    // ModelParametersComplexType
    //

    const ModelParametersComplexType::VersionType ModelParametersComplexType::version_default_value_ (
      "1.5");

    ModelParametersComplexType::
    ModelParametersComplexType ()
    : ::xml_schema::Type (),
      modifierType_ (::xml_schema::Flags (), this),
      group_ (::xml_schema::Flags (), this),
      version_ (getVersionDefaultValue (), ::xml_schema::Flags (), this)
    {
    }

    ModelParametersComplexType::
    ModelParametersComplexType (const ModelParametersComplexType& x,
                                ::xml_schema::Flags f,
                                ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      modifierType_ (x.modifierType_, f, this),
      group_ (x.group_, f, this),
      version_ (x.version_, f, this)
    {
    }

    ModelParametersComplexType::
    ModelParametersComplexType (const ::xercesc::DOMElement& e,
                                ::xml_schema::Flags f,
                                ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      modifierType_ (f, this),
      group_ (f, this),
      version_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
        this->parse (p, f);
      }
    }

    void ModelParametersComplexType::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_elements (); p.next_element ())
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // modifierType
        //
        if (n.name () == "modifierType" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< ModifierTypeType > r (
            ModifierTypeTraits::create (i, f, this));

          this->modifierType_.push_back (r);
          continue;
        }

        // group
        //
        if (n.name () == "group" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< GroupType > r (
            GroupTraits::create (i, f, this));

          this->group_.push_back (r);
          continue;
        }

        break;
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "version" && n.namespace_ ().empty ())
        {
          ::std::auto_ptr< VersionType > r (
            VersionTraits::create (i, f, this));

          this->version_.set (r);
          continue;
        }
      }

      if (!version_.present ())
      {
        this->version_.set (getVersionDefaultValue ());
      }
    }

    ModelParametersComplexType* ModelParametersComplexType::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class ModelParametersComplexType (*this, f, c);
    }

    ModelParametersComplexType::
    ~ModelParametersComplexType ()
    {
    }

    // ModelParameterGroupComplexType
    //

    ModelParameterGroupComplexType::
    ModelParameterGroupComplexType (const IdType& id)
    : ::xml_schema::Type (),
      description_ (::xml_schema::Flags (), this),
      locationId_ (::xml_schema::Flags (), this),
      model_ (::xml_schema::Flags (), this),
      validPeriod_ (::xml_schema::Flags (), this),
      parameter_ (::xml_schema::Flags (), this),
      ensemble_ (::xml_schema::Flags (), this),
      id_ (id, ::xml_schema::Flags (), this),
      name_ (::xml_schema::Flags (), this),
      readonly_ (getReadonlyDefaultValue (), ::xml_schema::Flags (), this),
      modified_ (getModifiedDefaultValue (), ::xml_schema::Flags (), this)
    {
    }

    ModelParameterGroupComplexType::
    ModelParameterGroupComplexType (const ModelParameterGroupComplexType& x,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      description_ (x.description_, f, this),
      locationId_ (x.locationId_, f, this),
      model_ (x.model_, f, this),
      validPeriod_ (x.validPeriod_, f, this),
      parameter_ (x.parameter_, f, this),
      ensemble_ (x.ensemble_, f, this),
      id_ (x.id_, f, this),
      name_ (x.name_, f, this),
      readonly_ (x.readonly_, f, this),
      modified_ (x.modified_, f, this)
    {
    }

    ModelParameterGroupComplexType::
    ModelParameterGroupComplexType (const ::xercesc::DOMElement& e,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      description_ (f, this),
      locationId_ (f, this),
      model_ (f, this),
      validPeriod_ (f, this),
      parameter_ (f, this),
      ensemble_ (f, this),
      id_ (f, this),
      name_ (f, this),
      readonly_ (f, this),
      modified_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
        this->parse (p, f);
      }
    }

    void ModelParameterGroupComplexType::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_elements (); p.next_element ())
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // description
        //
        if (n.name () == "description" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< DescriptionType > r (
            DescriptionTraits::create (i, f, this));

          if (!this->description_)
          {
            this->description_.set (r);
            continue;
          }
        }

        // locationId
        //
        if (n.name () == "locationId" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< LocationIdType > r (
            LocationIdTraits::create (i, f, this));

          if (!this->locationId_)
          {
            this->locationId_.set (r);
            continue;
          }
        }

        // model
        //
        if (n.name () == "model" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< ModelType > r (
            ModelTraits::create (i, f, this));

          if (!this->model_)
          {
            this->model_.set (r);
            continue;
          }
        }

        // validPeriod
        //
        if (n.name () == "validPeriod" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< ValidPeriodType > r (
            ValidPeriodTraits::create (i, f, this));

          if (!this->validPeriod_)
          {
            this->validPeriod_.set (r);
            continue;
          }
        }

        // parameter
        //
        if (n.name () == "parameter" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< ParameterType > r (
            ParameterTraits::create (i, f, this));

          this->parameter_.push_back (r);
          continue;
        }

        // ensemble
        //
        if (n.name () == "ensemble" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< EnsembleType > r (
            EnsembleTraits::create (i, f, this));

          this->ensemble_.push_back (r);
          continue;
        }

        break;
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "id" && n.namespace_ ().empty ())
        {
          ::std::auto_ptr< IdType > r (
            IdTraits::create (i, f, this));

          this->id_.set (r);
          continue;
        }

        if (n.name () == "name" && n.namespace_ ().empty ())
        {
          ::std::auto_ptr< NameType > r (
            NameTraits::create (i, f, this));

          this->name_.set (r);
          continue;
        }

        if (n.name () == "readonly" && n.namespace_ ().empty ())
        {
          this->readonly_.set (ReadonlyTraits::create (i, f, this));
          continue;
        }

        if (n.name () == "modified" && n.namespace_ ().empty ())
        {
          this->modified_.set (ModifiedTraits::create (i, f, this));
          continue;
        }
      }

      if (!id_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< char > (
          "id",
          "");
      }

      if (!readonly_.present ())
      {
        this->readonly_.set (getReadonlyDefaultValue ());
      }

      if (!modified_.present ())
      {
        this->modified_.set (getModifiedDefaultValue ());
      }
    }

    ModelParameterGroupComplexType* ModelParameterGroupComplexType::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class ModelParameterGroupComplexType (*this, f, c);
    }

    ModelParameterGroupComplexType::
    ~ModelParameterGroupComplexType ()
    {
    }

    // ModelParameterComplexType
    //

    ModelParameterComplexType::
    ModelParameterComplexType (const IdType& id)
    : ::xml_schema::Type (),
      description_ (::xml_schema::Flags (), this),
      dblValue_ (::xml_schema::Flags (), this),
      intValue_ (::xml_schema::Flags (), this),
      boolValue_ (::xml_schema::Flags (), this),
      stringValue_ (::xml_schema::Flags (), this),
      dateTimeValue_ (::xml_schema::Flags (), this),
      table_ (::xml_schema::Flags (), this),
      id_ (id, ::xml_schema::Flags (), this),
      name_ (::xml_schema::Flags (), this)
    {
    }

    ModelParameterComplexType::
    ModelParameterComplexType (const ModelParameterComplexType& x,
                               ::xml_schema::Flags f,
                               ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      description_ (x.description_, f, this),
      dblValue_ (x.dblValue_, f, this),
      intValue_ (x.intValue_, f, this),
      boolValue_ (x.boolValue_, f, this),
      stringValue_ (x.stringValue_, f, this),
      dateTimeValue_ (x.dateTimeValue_, f, this),
      table_ (x.table_, f, this),
      id_ (x.id_, f, this),
      name_ (x.name_, f, this)
    {
    }

    ModelParameterComplexType::
    ModelParameterComplexType (const ::xercesc::DOMElement& e,
                               ::xml_schema::Flags f,
                               ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      description_ (f, this),
      dblValue_ (f, this),
      intValue_ (f, this),
      boolValue_ (f, this),
      stringValue_ (f, this),
      dateTimeValue_ (f, this),
      table_ (f, this),
      id_ (f, this),
      name_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
        this->parse (p, f);
      }
    }

    void ModelParameterComplexType::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_elements (); p.next_element ())
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // description
        //
        if (n.name () == "description" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< DescriptionType > r (
            DescriptionTraits::create (i, f, this));

          if (!this->description_)
          {
            this->description_.set (r);
            continue;
          }
        }

        // dblValue
        //
        if (n.name () == "dblValue" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< DblValueType > r (
            DblValueTraits::create (i, f, this));

          if (!this->dblValue_)
          {
            this->dblValue_.set (r);
            continue;
          }
        }

        // intValue
        //
        if (n.name () == "intValue" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< IntValueType > r (
            IntValueTraits::create (i, f, this));

          if (!this->intValue_)
          {
            this->intValue_.set (r);
            continue;
          }
        }

        // boolValue
        //
        if (n.name () == "boolValue" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< BoolValueType > r (
            BoolValueTraits::create (i, f, this));

          if (!this->boolValue_)
          {
            this->boolValue_.set (r);
            continue;
          }
        }

        // stringValue
        //
        if (n.name () == "stringValue" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< StringValueType > r (
            StringValueTraits::create (i, f, this));

          if (!this->stringValue_)
          {
            this->stringValue_.set (r);
            continue;
          }
        }

        // dateTimeValue
        //
        if (n.name () == "dateTimeValue" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< DateTimeValueType > r (
            DateTimeValueTraits::create (i, f, this));

          if (!this->dateTimeValue_)
          {
            this->dateTimeValue_.set (r);
            continue;
          }
        }

        // table
        //
        if (n.name () == "table" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< TableType > r (
            TableTraits::create (i, f, this));

          if (!this->table_)
          {
            this->table_.set (r);
            continue;
          }
        }

        break;
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "id" && n.namespace_ ().empty ())
        {
          ::std::auto_ptr< IdType > r (
            IdTraits::create (i, f, this));

          this->id_.set (r);
          continue;
        }

        if (n.name () == "name" && n.namespace_ ().empty ())
        {
          ::std::auto_ptr< NameType > r (
            NameTraits::create (i, f, this));

          this->name_.set (r);
          continue;
        }
      }

      if (!id_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< char > (
          "id",
          "");
      }
    }

    ModelParameterComplexType* ModelParameterComplexType::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class ModelParameterComplexType (*this, f, c);
    }

    ModelParameterComplexType::
    ~ModelParameterComplexType ()
    {
    }

    // EnsembleComplexType
    //

    EnsembleComplexType::
    EnsembleComplexType (const IdType& id)
    : ::xml_schema::Type (),
      ensembleMember_ (::xml_schema::Flags (), this),
      ensembleMemberRange_ (::xml_schema::Flags (), this),
      parameter_ (::xml_schema::Flags (), this),
      id_ (id, ::xml_schema::Flags (), this)
    {
    }

    EnsembleComplexType::
    EnsembleComplexType (const EnsembleComplexType& x,
                         ::xml_schema::Flags f,
                         ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      ensembleMember_ (x.ensembleMember_, f, this),
      ensembleMemberRange_ (x.ensembleMemberRange_, f, this),
      parameter_ (x.parameter_, f, this),
      id_ (x.id_, f, this)
    {
    }

    EnsembleComplexType::
    EnsembleComplexType (const ::xercesc::DOMElement& e,
                         ::xml_schema::Flags f,
                         ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      ensembleMember_ (f, this),
      ensembleMemberRange_ (f, this),
      parameter_ (f, this),
      id_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
        this->parse (p, f);
      }
    }

    void EnsembleComplexType::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_elements (); p.next_element ())
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // ensembleMember
        //
        if (n.name () == "ensembleMember" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< EnsembleMemberType > r (
            EnsembleMemberTraits::create (i, f, this));

          if (!this->ensembleMember_)
          {
            this->ensembleMember_.set (r);
            continue;
          }
        }

        // ensembleMemberRange
        //
        if (n.name () == "ensembleMemberRange" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< EnsembleMemberRangeType > r (
            EnsembleMemberRangeTraits::create (i, f, this));

          if (!this->ensembleMemberRange_)
          {
            this->ensembleMemberRange_.set (r);
            continue;
          }
        }

        // parameter
        //
        if (n.name () == "parameter" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< ParameterType > r (
            ParameterTraits::create (i, f, this));

          this->parameter_.push_back (r);
          continue;
        }

        break;
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "id" && n.namespace_ ().empty ())
        {
          ::std::auto_ptr< IdType > r (
            IdTraits::create (i, f, this));

          this->id_.set (r);
          continue;
        }
      }

      if (!id_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< char > (
          "id",
          "");
      }
    }

    EnsembleComplexType* EnsembleComplexType::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class EnsembleComplexType (*this, f, c);
    }

    EnsembleComplexType::
    ~EnsembleComplexType ()
    {
    }
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace fews
{
  namespace PI
  {
    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (const ::std::string& u,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
        ::fews::PI::parseParameters (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (const ::std::string& u,
                     ::xml_schema::ErrorHandler& h,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
        ::fews::PI::parseParameters (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (const ::std::string& u,
                     ::xercesc::DOMErrorHandler& h,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
        ::fews::PI::parseParameters (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::std::istream& is,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::fews::PI::parseParameters (isrc, f, p);
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::std::istream& is,
                     ::xml_schema::ErrorHandler& h,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::fews::PI::parseParameters (isrc, h, f, p);
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::std::istream& is,
                     ::xercesc::DOMErrorHandler& h,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::fews::PI::parseParameters (isrc, h, f, p);
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::std::istream& is,
                     const ::std::string& sid,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::fews::PI::parseParameters (isrc, f, p);
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::std::istream& is,
                     const ::std::string& sid,
                     ::xml_schema::ErrorHandler& h,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::fews::PI::parseParameters (isrc, h, f, p);
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::std::istream& is,
                     const ::std::string& sid,
                     ::xercesc::DOMErrorHandler& h,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::fews::PI::parseParameters (isrc, h, f, p);
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::xercesc::InputSource& i,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
        ::fews::PI::parseParameters (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::xercesc::InputSource& i,
                     ::xml_schema::ErrorHandler& h,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
        ::fews::PI::parseParameters (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::xercesc::InputSource& i,
                     ::xercesc::DOMErrorHandler& h,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
        ::fews::PI::parseParameters (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (const ::xercesc::DOMDocument& d,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties& p)
    {
      if (f & ::xml_schema::Flags::keep_dom)
      {
        ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
          static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

        ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
          ::fews::PI::parseParameters (
            c, f | ::xml_schema::Flags::own_dom, p));

        return r;
      }

      const ::xercesc::DOMElement& e (*d.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "parameters" &&
          n.namespace_ () == "http://www.wldelft.nl/fews/PI")
      {
        ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
          ::xsd::cxx::tree::traits< ::fews::PI::ModelParametersComplexType, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "parameters",
        "http://www.wldelft.nl/fews/PI");
    }

    ::std::auto_ptr< ::fews::PI::ModelParametersComplexType >
    parseParameters (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
                     ::xml_schema::Flags f,
                     const ::xml_schema::Properties&)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
        ((f & ::xml_schema::Flags::keep_dom) &&
         !(f & ::xml_schema::Flags::own_dom))
        ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
        : 0);

      ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
      const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (f & ::xml_schema::Flags::keep_dom)
        doc.setUserData (::xml_schema::dom::treeNodeKey,
                         (c.get () ? &c : &d),
                         0);

      if (n.name () == "parameters" &&
          n.namespace_ () == "http://www.wldelft.nl/fews/PI")
      {
        ::std::auto_ptr< ::fews::PI::ModelParametersComplexType > r (
          ::xsd::cxx::tree::traits< ::fews::PI::ModelParametersComplexType, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "parameters",
        "http://www.wldelft.nl/fews/PI");
    }
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace fews
{
  namespace PI
  {
    void
    serializeParameters (::std::ostream& o,
                         const ::fews::PI::ModelParametersComplexType& s,
                         const ::xml_schema::NamespaceInfomap& m,
                         const ::std::string& e,
                         ::xml_schema::Flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0);

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeParameters (s, m, f));

      ::xsd::cxx::tree::error_handler< char > h;

      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
      }
    }

    void
    serializeParameters (::std::ostream& o,
                         const ::fews::PI::ModelParametersComplexType& s,
                         ::xml_schema::ErrorHandler& h,
                         const ::xml_schema::NamespaceInfomap& m,
                         const ::std::string& e,
                         ::xml_schema::Flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0);

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeParameters (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    serializeParameters (::std::ostream& o,
                         const ::fews::PI::ModelParametersComplexType& s,
                         ::xercesc::DOMErrorHandler& h,
                         const ::xml_schema::NamespaceInfomap& m,
                         const ::std::string& e,
                         ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeParameters (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    serializeParameters (::xercesc::XMLFormatTarget& t,
                         const ::fews::PI::ModelParametersComplexType& s,
                         const ::xml_schema::NamespaceInfomap& m,
                         const ::std::string& e,
                         ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeParameters (s, m, f));

      ::xsd::cxx::tree::error_handler< char > h;

      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
      }
    }

    void
    serializeParameters (::xercesc::XMLFormatTarget& t,
                         const ::fews::PI::ModelParametersComplexType& s,
                         ::xml_schema::ErrorHandler& h,
                         const ::xml_schema::NamespaceInfomap& m,
                         const ::std::string& e,
                         ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeParameters (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    serializeParameters (::xercesc::XMLFormatTarget& t,
                         const ::fews::PI::ModelParametersComplexType& s,
                         ::xercesc::DOMErrorHandler& h,
                         const ::xml_schema::NamespaceInfomap& m,
                         const ::std::string& e,
                         ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeParameters (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    serializeParameters (::xercesc::DOMDocument& d,
                         const ::fews::PI::ModelParametersComplexType& s,
                         ::xml_schema::Flags)
    {
      ::xercesc::DOMElement& e (*d.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "parameters" &&
          n.namespace_ () == "http://www.wldelft.nl/fews/PI")
      {
        e << s;
      }
      else
      {
        throw ::xsd::cxx::tree::unexpected_element < char > (
          n.name (),
          n.namespace_ (),
          "parameters",
          "http://www.wldelft.nl/fews/PI");
      }
    }

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
    serializeParameters (const ::fews::PI::ModelParametersComplexType& s,
                         const ::xml_schema::NamespaceInfomap& m,
                         ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::serialize< char > (
          "parameters",
          "http://www.wldelft.nl/fews/PI",
          m, f));

      ::fews::PI::serializeParameters (*d, s, f);
      return d;
    }

    void
    operator<< (::xercesc::DOMElement& e, const ModelParametersComplexType& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // modifierType
      //
      for (ModelParametersComplexType::ModifierTypeConstIterator
           b (i.getModifierType ().begin ()), n (i.getModifierType ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "modifierType",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // group
      //
      for (ModelParametersComplexType::GroupConstIterator
           b (i.getGroup ().begin ()), n (i.getGroup ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "group",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // version
      //
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "version",
            e));

        a << i.getVersion ();
      }
    }

    void
    operator<< (::xercesc::DOMElement& e, const ModelParameterGroupComplexType& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // description
      //
      if (i.getDescription ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "description",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getDescription ();
      }

      // locationId
      //
      if (i.getLocationId ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "locationId",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getLocationId ();
      }

      // model
      //
      if (i.getModel ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "model",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getModel ();
      }

      // validPeriod
      //
      if (i.getValidPeriod ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "validPeriod",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getValidPeriod ();
      }

      // parameter
      //
      for (ModelParameterGroupComplexType::ParameterConstIterator
           b (i.getParameter ().begin ()), n (i.getParameter ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "parameter",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // ensemble
      //
      for (ModelParameterGroupComplexType::EnsembleConstIterator
           b (i.getEnsemble ().begin ()), n (i.getEnsemble ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "ensemble",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // id
      //
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "id",
            e));

        a << i.getId ();
      }

      // name
      //
      if (i.getName ())
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "name",
            e));

        a << *i.getName ();
      }

      // readonly
      //
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "readonly",
            e));

        a << i.getReadonly ();
      }

      // modified
      //
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "modified",
            e));

        a << i.getModified ();
      }
    }

    void
    operator<< (::xercesc::DOMElement& e, const ModelParameterComplexType& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // description
      //
      if (i.getDescription ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "description",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getDescription ();
      }

      // dblValue
      //
      if (i.getDblValue ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "dblValue",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getDblValue ();
      }

      // intValue
      //
      if (i.getIntValue ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "intValue",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getIntValue ();
      }

      // boolValue
      //
      if (i.getBoolValue ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "boolValue",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getBoolValue ();
      }

      // stringValue
      //
      if (i.getStringValue ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "stringValue",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getStringValue ();
      }

      // dateTimeValue
      //
      if (i.getDateTimeValue ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "dateTimeValue",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getDateTimeValue ();
      }

      // table
      //
      if (i.getTable ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "table",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getTable ();
      }

      // id
      //
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "id",
            e));

        a << i.getId ();
      }

      // name
      //
      if (i.getName ())
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "name",
            e));

        a << *i.getName ();
      }
    }

    void
    operator<< (::xercesc::DOMElement& e, const EnsembleComplexType& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // ensembleMember
      //
      if (i.getEnsembleMember ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "ensembleMember",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getEnsembleMember ();
      }

      // ensembleMemberRange
      //
      if (i.getEnsembleMemberRange ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "ensembleMemberRange",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getEnsembleMemberRange ();
      }

      // parameter
      //
      for (EnsembleComplexType::ParameterConstIterator
           b (i.getParameter ().begin ()), n (i.getParameter ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "parameter",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // id
      //
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "id",
            e));

        a << i.getId ();
      }
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

