// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "pi_run.hxx"

namespace fews
{
  namespace PI
  {
    // RunComplexType
    // 

    const RunComplexType::LogLevelOptional& RunComplexType::
    getLogLevel () const
    {
      return this->logLevel_;
    }

    RunComplexType::LogLevelOptional& RunComplexType::
    getLogLevel ()
    {
      return this->logLevel_;
    }

    void RunComplexType::
    setLogLevel (const LogLevelType& x)
    {
      this->logLevel_.set (x);
    }

    void RunComplexType::
    setLogLevel (const LogLevelOptional& x)
    {
      this->logLevel_ = x;
    }

    void RunComplexType::
    setLogLevel (::std::auto_ptr< LogLevelType > x)
    {
      this->logLevel_.set (x);
    }

    const RunComplexType::TimeZoneType& RunComplexType::
    getTimeZone () const
    {
      return this->timeZone_.get ();
    }

    RunComplexType::TimeZoneType& RunComplexType::
    getTimeZone ()
    {
      return this->timeZone_.get ();
    }

    void RunComplexType::
    setTimeZone (const TimeZoneType& x)
    {
      this->timeZone_.set (x);
    }

    void RunComplexType::
    setTimeZone (::std::auto_ptr< TimeZoneType > x)
    {
      this->timeZone_.set (x);
    }

    const RunComplexType::StartDateTimeType& RunComplexType::
    getStartDateTime () const
    {
      return this->startDateTime_.get ();
    }

    RunComplexType::StartDateTimeType& RunComplexType::
    getStartDateTime ()
    {
      return this->startDateTime_.get ();
    }

    void RunComplexType::
    setStartDateTime (const StartDateTimeType& x)
    {
      this->startDateTime_.set (x);
    }

    void RunComplexType::
    setStartDateTime (::std::auto_ptr< StartDateTimeType > x)
    {
      this->startDateTime_.set (x);
    }

    const RunComplexType::EndDateTimeType& RunComplexType::
    getEndDateTime () const
    {
      return this->endDateTime_.get ();
    }

    RunComplexType::EndDateTimeType& RunComplexType::
    getEndDateTime ()
    {
      return this->endDateTime_.get ();
    }

    void RunComplexType::
    setEndDateTime (const EndDateTimeType& x)
    {
      this->endDateTime_.set (x);
    }

    void RunComplexType::
    setEndDateTime (::std::auto_ptr< EndDateTimeType > x)
    {
      this->endDateTime_.set (x);
    }

    const RunComplexType::Time0Type& RunComplexType::
    getTime0 () const
    {
      return this->time0_.get ();
    }

    RunComplexType::Time0Type& RunComplexType::
    getTime0 ()
    {
      return this->time0_.get ();
    }

    void RunComplexType::
    setTime0 (const Time0Type& x)
    {
      this->time0_.set (x);
    }

    void RunComplexType::
    setTime0 (::std::auto_ptr< Time0Type > x)
    {
      this->time0_.set (x);
    }

    const RunComplexType::LastObservationDateTimeOptional& RunComplexType::
    getLastObservationDateTime () const
    {
      return this->lastObservationDateTime_;
    }

    RunComplexType::LastObservationDateTimeOptional& RunComplexType::
    getLastObservationDateTime ()
    {
      return this->lastObservationDateTime_;
    }

    void RunComplexType::
    setLastObservationDateTime (const LastObservationDateTimeType& x)
    {
      this->lastObservationDateTime_.set (x);
    }

    void RunComplexType::
    setLastObservationDateTime (const LastObservationDateTimeOptional& x)
    {
      this->lastObservationDateTime_ = x;
    }

    void RunComplexType::
    setLastObservationDateTime (::std::auto_ptr< LastObservationDateTimeType > x)
    {
      this->lastObservationDateTime_.set (x);
    }

    const RunComplexType::WorkDirType& RunComplexType::
    getWorkDir () const
    {
      return this->workDir_.get ();
    }

    RunComplexType::WorkDirType& RunComplexType::
    getWorkDir ()
    {
      return this->workDir_.get ();
    }

    void RunComplexType::
    setWorkDir (const WorkDirType& x)
    {
      this->workDir_.set (x);
    }

    void RunComplexType::
    setWorkDir (::std::auto_ptr< WorkDirType > x)
    {
      this->workDir_.set (x);
    }

    const RunComplexType::InputParameterFileSequence& RunComplexType::
    getInputParameterFile () const
    {
      return this->inputParameterFile_;
    }

    RunComplexType::InputParameterFileSequence& RunComplexType::
    getInputParameterFile ()
    {
      return this->inputParameterFile_;
    }

    void RunComplexType::
    setInputParameterFile (const InputParameterFileSequence& s)
    {
      this->inputParameterFile_ = s;
    }

    const RunComplexType::InputStateDescriptionFileSequence& RunComplexType::
    getInputStateDescriptionFile () const
    {
      return this->inputStateDescriptionFile_;
    }

    RunComplexType::InputStateDescriptionFileSequence& RunComplexType::
    getInputStateDescriptionFile ()
    {
      return this->inputStateDescriptionFile_;
    }

    void RunComplexType::
    setInputStateDescriptionFile (const InputStateDescriptionFileSequence& s)
    {
      this->inputStateDescriptionFile_ = s;
    }

    const RunComplexType::InputTimeSeriesFileSequence& RunComplexType::
    getInputTimeSeriesFile () const
    {
      return this->inputTimeSeriesFile_;
    }

    RunComplexType::InputTimeSeriesFileSequence& RunComplexType::
    getInputTimeSeriesFile ()
    {
      return this->inputTimeSeriesFile_;
    }

    void RunComplexType::
    setInputTimeSeriesFile (const InputTimeSeriesFileSequence& s)
    {
      this->inputTimeSeriesFile_ = s;
    }

    const RunComplexType::InputMapStackFileSequence& RunComplexType::
    getInputMapStackFile () const
    {
      return this->inputMapStackFile_;
    }

    RunComplexType::InputMapStackFileSequence& RunComplexType::
    getInputMapStackFile ()
    {
      return this->inputMapStackFile_;
    }

    void RunComplexType::
    setInputMapStackFile (const InputMapStackFileSequence& s)
    {
      this->inputMapStackFile_ = s;
    }

    const RunComplexType::InputNetcdfFileSequence& RunComplexType::
    getInputNetcdfFile () const
    {
      return this->inputNetcdfFile_;
    }

    RunComplexType::InputNetcdfFileSequence& RunComplexType::
    getInputNetcdfFile ()
    {
      return this->inputNetcdfFile_;
    }

    void RunComplexType::
    setInputNetcdfFile (const InputNetcdfFileSequence& s)
    {
      this->inputNetcdfFile_ = s;
    }

    const RunComplexType::InputLongitudinalProfilesFileSequence& RunComplexType::
    getInputLongitudinalProfilesFile () const
    {
      return this->inputLongitudinalProfilesFile_;
    }

    RunComplexType::InputLongitudinalProfilesFileSequence& RunComplexType::
    getInputLongitudinalProfilesFile ()
    {
      return this->inputLongitudinalProfilesFile_;
    }

    void RunComplexType::
    setInputLongitudinalProfilesFile (const InputLongitudinalProfilesFileSequence& s)
    {
      this->inputLongitudinalProfilesFile_ = s;
    }

    const RunComplexType::InputRatingCurveFileSequence& RunComplexType::
    getInputRatingCurveFile () const
    {
      return this->inputRatingCurveFile_;
    }

    RunComplexType::InputRatingCurveFileSequence& RunComplexType::
    getInputRatingCurveFile ()
    {
      return this->inputRatingCurveFile_;
    }

    void RunComplexType::
    setInputRatingCurveFile (const InputRatingCurveFileSequence& s)
    {
      this->inputRatingCurveFile_ = s;
    }

    const RunComplexType::OutputDiagnosticFileType& RunComplexType::
    getOutputDiagnosticFile () const
    {
      return this->outputDiagnosticFile_.get ();
    }

    RunComplexType::OutputDiagnosticFileType& RunComplexType::
    getOutputDiagnosticFile ()
    {
      return this->outputDiagnosticFile_.get ();
    }

    void RunComplexType::
    setOutputDiagnosticFile (const OutputDiagnosticFileType& x)
    {
      this->outputDiagnosticFile_.set (x);
    }

    void RunComplexType::
    setOutputDiagnosticFile (::std::auto_ptr< OutputDiagnosticFileType > x)
    {
      this->outputDiagnosticFile_.set (x);
    }

    const RunComplexType::OutputStateDescriptionFileOptional& RunComplexType::
    getOutputStateDescriptionFile () const
    {
      return this->outputStateDescriptionFile_;
    }

    RunComplexType::OutputStateDescriptionFileOptional& RunComplexType::
    getOutputStateDescriptionFile ()
    {
      return this->outputStateDescriptionFile_;
    }

    void RunComplexType::
    setOutputStateDescriptionFile (const OutputStateDescriptionFileType& x)
    {
      this->outputStateDescriptionFile_.set (x);
    }

    void RunComplexType::
    setOutputStateDescriptionFile (const OutputStateDescriptionFileOptional& x)
    {
      this->outputStateDescriptionFile_ = x;
    }

    void RunComplexType::
    setOutputStateDescriptionFile (::std::auto_ptr< OutputStateDescriptionFileType > x)
    {
      this->outputStateDescriptionFile_.set (x);
    }

    const RunComplexType::OutputTimeSeriesFileSequence& RunComplexType::
    getOutputTimeSeriesFile () const
    {
      return this->outputTimeSeriesFile_;
    }

    RunComplexType::OutputTimeSeriesFileSequence& RunComplexType::
    getOutputTimeSeriesFile ()
    {
      return this->outputTimeSeriesFile_;
    }

    void RunComplexType::
    setOutputTimeSeriesFile (const OutputTimeSeriesFileSequence& s)
    {
      this->outputTimeSeriesFile_ = s;
    }

    const RunComplexType::OutputMapStackFileSequence& RunComplexType::
    getOutputMapStackFile () const
    {
      return this->outputMapStackFile_;
    }

    RunComplexType::OutputMapStackFileSequence& RunComplexType::
    getOutputMapStackFile ()
    {
      return this->outputMapStackFile_;
    }

    void RunComplexType::
    setOutputMapStackFile (const OutputMapStackFileSequence& s)
    {
      this->outputMapStackFile_ = s;
    }

    const RunComplexType::OutputNetcdfFileSequence& RunComplexType::
    getOutputNetcdfFile () const
    {
      return this->outputNetcdfFile_;
    }

    RunComplexType::OutputNetcdfFileSequence& RunComplexType::
    getOutputNetcdfFile ()
    {
      return this->outputNetcdfFile_;
    }

    void RunComplexType::
    setOutputNetcdfFile (const OutputNetcdfFileSequence& s)
    {
      this->outputNetcdfFile_ = s;
    }

    const RunComplexType::OutputLongitudinalProfilesFileSequence& RunComplexType::
    getOutputLongitudinalProfilesFile () const
    {
      return this->outputLongitudinalProfilesFile_;
    }

    RunComplexType::OutputLongitudinalProfilesFileSequence& RunComplexType::
    getOutputLongitudinalProfilesFile ()
    {
      return this->outputLongitudinalProfilesFile_;
    }

    void RunComplexType::
    setOutputLongitudinalProfilesFile (const OutputLongitudinalProfilesFileSequence& s)
    {
      this->outputLongitudinalProfilesFile_ = s;
    }

    const RunComplexType::OutputCsvModuleRunTableFileSequence& RunComplexType::
    getOutputCsvModuleRunTableFile () const
    {
      return this->outputCsvModuleRunTableFile_;
    }

    RunComplexType::OutputCsvModuleRunTableFileSequence& RunComplexType::
    getOutputCsvModuleRunTableFile ()
    {
      return this->outputCsvModuleRunTableFile_;
    }

    void RunComplexType::
    setOutputCsvModuleRunTableFile (const OutputCsvModuleRunTableFileSequence& s)
    {
      this->outputCsvModuleRunTableFile_ = s;
    }

    const RunComplexType::PropertiesOptional& RunComplexType::
    getProperties () const
    {
      return this->properties_;
    }

    RunComplexType::PropertiesOptional& RunComplexType::
    getProperties ()
    {
      return this->properties_;
    }

    void RunComplexType::
    setProperties (const PropertiesType& x)
    {
      this->properties_.set (x);
    }

    void RunComplexType::
    setProperties (const PropertiesOptional& x)
    {
      this->properties_ = x;
    }

    void RunComplexType::
    setProperties (::std::auto_ptr< PropertiesType > x)
    {
      this->properties_.set (x);
    }

    const RunComplexType::VersionType& RunComplexType::
    getVersion () const
    {
      return this->version_.get ();
    }

    RunComplexType::VersionType& RunComplexType::
    getVersion ()
    {
      return this->version_.get ();
    }

    void RunComplexType::
    setVersion (const VersionType& x)
    {
      this->version_.set (x);
    }

    void RunComplexType::
    setVersion (::std::auto_ptr< VersionType > x)
    {
      this->version_.set (x);
    }


    // LogLevelString
    // 

    LogLevelString::
    LogLevelString (Value v)
    : ::xml_schema::String (_xsd_LogLevelString_literals_[v])
    {
    }

    LogLevelString::
    LogLevelString (const char* v)
    : ::xml_schema::String (v)
    {
    }

    LogLevelString::
    LogLevelString (const ::std::string& v)
    : ::xml_schema::String (v)
    {
    }

    LogLevelString::
    LogLevelString (const ::xml_schema::String& v)
    : ::xml_schema::String (v)
    {
    }

    LogLevelString::
    LogLevelString (const LogLevelString& v,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::String (v, f, c)
    {
    }

    LogLevelString& LogLevelString::
    operator= (Value v)
    {
      static_cast< ::xml_schema::String& > (*this) = 
      ::xml_schema::String (_xsd_LogLevelString_literals_[v]);

      return *this;
    }
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace fews
{
  namespace PI
  {
    // RunComplexType
    //

    RunComplexType::
    RunComplexType (const TimeZoneType& timeZone,
                    const StartDateTimeType& startDateTime,
                    const EndDateTimeType& endDateTime,
                    const Time0Type& time0,
                    const WorkDirType& workDir,
                    const OutputDiagnosticFileType& outputDiagnosticFile,
                    const VersionType& version)
    : ::xml_schema::Type (),
      logLevel_ (::xml_schema::Flags (), this),
      timeZone_ (timeZone, ::xml_schema::Flags (), this),
      startDateTime_ (startDateTime, ::xml_schema::Flags (), this),
      endDateTime_ (endDateTime, ::xml_schema::Flags (), this),
      time0_ (time0, ::xml_schema::Flags (), this),
      lastObservationDateTime_ (::xml_schema::Flags (), this),
      workDir_ (workDir, ::xml_schema::Flags (), this),
      inputParameterFile_ (::xml_schema::Flags (), this),
      inputStateDescriptionFile_ (::xml_schema::Flags (), this),
      inputTimeSeriesFile_ (::xml_schema::Flags (), this),
      inputMapStackFile_ (::xml_schema::Flags (), this),
      inputNetcdfFile_ (::xml_schema::Flags (), this),
      inputLongitudinalProfilesFile_ (::xml_schema::Flags (), this),
      inputRatingCurveFile_ (::xml_schema::Flags (), this),
      outputDiagnosticFile_ (outputDiagnosticFile, ::xml_schema::Flags (), this),
      outputStateDescriptionFile_ (::xml_schema::Flags (), this),
      outputTimeSeriesFile_ (::xml_schema::Flags (), this),
      outputMapStackFile_ (::xml_schema::Flags (), this),
      outputNetcdfFile_ (::xml_schema::Flags (), this),
      outputLongitudinalProfilesFile_ (::xml_schema::Flags (), this),
      outputCsvModuleRunTableFile_ (::xml_schema::Flags (), this),
      properties_ (::xml_schema::Flags (), this),
      version_ (version, ::xml_schema::Flags (), this)
    {
    }

    RunComplexType::
    RunComplexType (const TimeZoneType& timeZone,
                    ::std::auto_ptr< StartDateTimeType >& startDateTime,
                    ::std::auto_ptr< EndDateTimeType >& endDateTime,
                    ::std::auto_ptr< Time0Type >& time0,
                    const WorkDirType& workDir,
                    const OutputDiagnosticFileType& outputDiagnosticFile,
                    const VersionType& version)
    : ::xml_schema::Type (),
      logLevel_ (::xml_schema::Flags (), this),
      timeZone_ (timeZone, ::xml_schema::Flags (), this),
      startDateTime_ (startDateTime, ::xml_schema::Flags (), this),
      endDateTime_ (endDateTime, ::xml_schema::Flags (), this),
      time0_ (time0, ::xml_schema::Flags (), this),
      lastObservationDateTime_ (::xml_schema::Flags (), this),
      workDir_ (workDir, ::xml_schema::Flags (), this),
      inputParameterFile_ (::xml_schema::Flags (), this),
      inputStateDescriptionFile_ (::xml_schema::Flags (), this),
      inputTimeSeriesFile_ (::xml_schema::Flags (), this),
      inputMapStackFile_ (::xml_schema::Flags (), this),
      inputNetcdfFile_ (::xml_schema::Flags (), this),
      inputLongitudinalProfilesFile_ (::xml_schema::Flags (), this),
      inputRatingCurveFile_ (::xml_schema::Flags (), this),
      outputDiagnosticFile_ (outputDiagnosticFile, ::xml_schema::Flags (), this),
      outputStateDescriptionFile_ (::xml_schema::Flags (), this),
      outputTimeSeriesFile_ (::xml_schema::Flags (), this),
      outputMapStackFile_ (::xml_schema::Flags (), this),
      outputNetcdfFile_ (::xml_schema::Flags (), this),
      outputLongitudinalProfilesFile_ (::xml_schema::Flags (), this),
      outputCsvModuleRunTableFile_ (::xml_schema::Flags (), this),
      properties_ (::xml_schema::Flags (), this),
      version_ (version, ::xml_schema::Flags (), this)
    {
    }

    RunComplexType::
    RunComplexType (const RunComplexType& x,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::Type (x, f, c),
      logLevel_ (x.logLevel_, f, this),
      timeZone_ (x.timeZone_, f, this),
      startDateTime_ (x.startDateTime_, f, this),
      endDateTime_ (x.endDateTime_, f, this),
      time0_ (x.time0_, f, this),
      lastObservationDateTime_ (x.lastObservationDateTime_, f, this),
      workDir_ (x.workDir_, f, this),
      inputParameterFile_ (x.inputParameterFile_, f, this),
      inputStateDescriptionFile_ (x.inputStateDescriptionFile_, f, this),
      inputTimeSeriesFile_ (x.inputTimeSeriesFile_, f, this),
      inputMapStackFile_ (x.inputMapStackFile_, f, this),
      inputNetcdfFile_ (x.inputNetcdfFile_, f, this),
      inputLongitudinalProfilesFile_ (x.inputLongitudinalProfilesFile_, f, this),
      inputRatingCurveFile_ (x.inputRatingCurveFile_, f, this),
      outputDiagnosticFile_ (x.outputDiagnosticFile_, f, this),
      outputStateDescriptionFile_ (x.outputStateDescriptionFile_, f, this),
      outputTimeSeriesFile_ (x.outputTimeSeriesFile_, f, this),
      outputMapStackFile_ (x.outputMapStackFile_, f, this),
      outputNetcdfFile_ (x.outputNetcdfFile_, f, this),
      outputLongitudinalProfilesFile_ (x.outputLongitudinalProfilesFile_, f, this),
      outputCsvModuleRunTableFile_ (x.outputCsvModuleRunTableFile_, f, this),
      properties_ (x.properties_, f, this),
      version_ (x.version_, f, this)
    {
    }

    RunComplexType::
    RunComplexType (const ::xercesc::DOMElement& e,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
      logLevel_ (f, this),
      timeZone_ (f, this),
      startDateTime_ (f, this),
      endDateTime_ (f, this),
      time0_ (f, this),
      lastObservationDateTime_ (f, this),
      workDir_ (f, this),
      inputParameterFile_ (f, this),
      inputStateDescriptionFile_ (f, this),
      inputTimeSeriesFile_ (f, this),
      inputMapStackFile_ (f, this),
      inputNetcdfFile_ (f, this),
      inputLongitudinalProfilesFile_ (f, this),
      inputRatingCurveFile_ (f, this),
      outputDiagnosticFile_ (f, this),
      outputStateDescriptionFile_ (f, this),
      outputTimeSeriesFile_ (f, this),
      outputMapStackFile_ (f, this),
      outputNetcdfFile_ (f, this),
      outputLongitudinalProfilesFile_ (f, this),
      outputCsvModuleRunTableFile_ (f, this),
      properties_ (f, this),
      version_ (f, this)
    {
      if ((f & ::xml_schema::Flags::base) == 0)
      {
        ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
        this->parse (p, f);
      }
    }

    void RunComplexType::
    parse (::xsd::cxx::xml::dom::parser< char >& p,
           ::xml_schema::Flags f)
    {
      for (; p.more_elements (); p.next_element ())
      {
        const ::xercesc::DOMElement& i (p.cur_element ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        // logLevel
        //
        if (n.name () == "logLevel" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< LogLevelType > r (
            LogLevelTraits::create (i, f, this));

          if (!this->logLevel_)
          {
            this->logLevel_.set (r);
            continue;
          }
        }

        // timeZone
        //
        if (n.name () == "timeZone" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< TimeZoneType > r (
            TimeZoneTraits::create (i, f, this));

          if (!timeZone_.present ())
          {
            this->timeZone_.set (r);
            continue;
          }
        }

        // startDateTime
        //
        if (n.name () == "startDateTime" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< StartDateTimeType > r (
            StartDateTimeTraits::create (i, f, this));

          if (!startDateTime_.present ())
          {
            this->startDateTime_.set (r);
            continue;
          }
        }

        // endDateTime
        //
        if (n.name () == "endDateTime" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< EndDateTimeType > r (
            EndDateTimeTraits::create (i, f, this));

          if (!endDateTime_.present ())
          {
            this->endDateTime_.set (r);
            continue;
          }
        }

        // time0
        //
        if (n.name () == "time0" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< Time0Type > r (
            Time0Traits::create (i, f, this));

          if (!time0_.present ())
          {
            this->time0_.set (r);
            continue;
          }
        }

        // lastObservationDateTime
        //
        if (n.name () == "lastObservationDateTime" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< LastObservationDateTimeType > r (
            LastObservationDateTimeTraits::create (i, f, this));

          if (!this->lastObservationDateTime_)
          {
            this->lastObservationDateTime_.set (r);
            continue;
          }
        }

        // workDir
        //
        if (n.name () == "workDir" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< WorkDirType > r (
            WorkDirTraits::create (i, f, this));

          if (!workDir_.present ())
          {
            this->workDir_.set (r);
            continue;
          }
        }

        // inputParameterFile
        //
        if (n.name () == "inputParameterFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< InputParameterFileType > r (
            InputParameterFileTraits::create (i, f, this));

          this->inputParameterFile_.push_back (r);
          continue;
        }

        // inputStateDescriptionFile
        //
        if (n.name () == "inputStateDescriptionFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< InputStateDescriptionFileType > r (
            InputStateDescriptionFileTraits::create (i, f, this));

          this->inputStateDescriptionFile_.push_back (r);
          continue;
        }

        // inputTimeSeriesFile
        //
        if (n.name () == "inputTimeSeriesFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< InputTimeSeriesFileType > r (
            InputTimeSeriesFileTraits::create (i, f, this));

          this->inputTimeSeriesFile_.push_back (r);
          continue;
        }

        // inputMapStackFile
        //
        if (n.name () == "inputMapStackFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< InputMapStackFileType > r (
            InputMapStackFileTraits::create (i, f, this));

          this->inputMapStackFile_.push_back (r);
          continue;
        }

        // inputNetcdfFile
        //
        if (n.name () == "inputNetcdfFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< InputNetcdfFileType > r (
            InputNetcdfFileTraits::create (i, f, this));

          this->inputNetcdfFile_.push_back (r);
          continue;
        }

        // inputLongitudinalProfilesFile
        //
        if (n.name () == "inputLongitudinalProfilesFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< InputLongitudinalProfilesFileType > r (
            InputLongitudinalProfilesFileTraits::create (i, f, this));

          this->inputLongitudinalProfilesFile_.push_back (r);
          continue;
        }

        // inputRatingCurveFile
        //
        if (n.name () == "inputRatingCurveFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< InputRatingCurveFileType > r (
            InputRatingCurveFileTraits::create (i, f, this));

          this->inputRatingCurveFile_.push_back (r);
          continue;
        }

        // outputDiagnosticFile
        //
        if (n.name () == "outputDiagnosticFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< OutputDiagnosticFileType > r (
            OutputDiagnosticFileTraits::create (i, f, this));

          if (!outputDiagnosticFile_.present ())
          {
            this->outputDiagnosticFile_.set (r);
            continue;
          }
        }

        // outputStateDescriptionFile
        //
        if (n.name () == "outputStateDescriptionFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< OutputStateDescriptionFileType > r (
            OutputStateDescriptionFileTraits::create (i, f, this));

          if (!this->outputStateDescriptionFile_)
          {
            this->outputStateDescriptionFile_.set (r);
            continue;
          }
        }

        // outputTimeSeriesFile
        //
        if (n.name () == "outputTimeSeriesFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< OutputTimeSeriesFileType > r (
            OutputTimeSeriesFileTraits::create (i, f, this));

          this->outputTimeSeriesFile_.push_back (r);
          continue;
        }

        // outputMapStackFile
        //
        if (n.name () == "outputMapStackFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< OutputMapStackFileType > r (
            OutputMapStackFileTraits::create (i, f, this));

          this->outputMapStackFile_.push_back (r);
          continue;
        }

        // outputNetcdfFile
        //
        if (n.name () == "outputNetcdfFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< OutputNetcdfFileType > r (
            OutputNetcdfFileTraits::create (i, f, this));

          this->outputNetcdfFile_.push_back (r);
          continue;
        }

        // outputLongitudinalProfilesFile
        //
        if (n.name () == "outputLongitudinalProfilesFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< OutputLongitudinalProfilesFileType > r (
            OutputLongitudinalProfilesFileTraits::create (i, f, this));

          this->outputLongitudinalProfilesFile_.push_back (r);
          continue;
        }

        // outputCsvModuleRunTableFile
        //
        if (n.name () == "outputCsvModuleRunTableFile" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< OutputCsvModuleRunTableFileType > r (
            OutputCsvModuleRunTableFileTraits::create (i, f, this));

          this->outputCsvModuleRunTableFile_.push_back (r);
          continue;
        }

        // properties
        //
        if (n.name () == "properties" && n.namespace_ () == "http://www.wldelft.nl/fews/PI")
        {
          ::std::auto_ptr< PropertiesType > r (
            PropertiesTraits::create (i, f, this));

          if (!this->properties_)
          {
            this->properties_.set (r);
            continue;
          }
        }

        break;
      }

      if (!timeZone_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "timeZone",
          "http://www.wldelft.nl/fews/PI");
      }

      if (!startDateTime_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "startDateTime",
          "http://www.wldelft.nl/fews/PI");
      }

      if (!endDateTime_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "endDateTime",
          "http://www.wldelft.nl/fews/PI");
      }

      if (!time0_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "time0",
          "http://www.wldelft.nl/fews/PI");
      }

      if (!workDir_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "workDir",
          "http://www.wldelft.nl/fews/PI");
      }

      if (!outputDiagnosticFile_.present ())
      {
        throw ::xsd::cxx::tree::expected_element< char > (
          "outputDiagnosticFile",
          "http://www.wldelft.nl/fews/PI");
      }

      while (p.more_attributes ())
      {
        const ::xercesc::DOMAttr& i (p.next_attribute ());
        const ::xsd::cxx::xml::qualified_name< char > n (
          ::xsd::cxx::xml::dom::name< char > (i));

        if (n.name () == "version" && n.namespace_ ().empty ())
        {
          ::std::auto_ptr< VersionType > r (
            VersionTraits::create (i, f, this));

          this->version_.set (r);
          continue;
        }
      }

      if (!version_.present ())
      {
        throw ::xsd::cxx::tree::expected_attribute< char > (
          "version",
          "");
      }
    }

    RunComplexType* RunComplexType::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class RunComplexType (*this, f, c);
    }

    RunComplexType::
    ~RunComplexType ()
    {
    }

    // LogLevelString
    //

    LogLevelString::
    LogLevelString (const ::xercesc::DOMElement& e,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::String (e, f, c)
    {
      _xsd_LogLevelString_convert ();
    }

    LogLevelString::
    LogLevelString (const ::xercesc::DOMAttr& a,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::String (a, f, c)
    {
      _xsd_LogLevelString_convert ();
    }

    LogLevelString::
    LogLevelString (const ::std::string& s,
                    const ::xercesc::DOMElement* e,
                    ::xml_schema::Flags f,
                    ::xml_schema::Container* c)
    : ::xml_schema::String (s, e, f, c)
    {
      _xsd_LogLevelString_convert ();
    }

    LogLevelString* LogLevelString::
    _clone (::xml_schema::Flags f,
            ::xml_schema::Container* c) const
    {
      return new class LogLevelString (*this, f, c);
    }

    LogLevelString::Value LogLevelString::
    _xsd_LogLevelString_convert () const
    {
      ::xsd::cxx::tree::enum_comparator< char > c (_xsd_LogLevelString_literals_);
      const Value* i (::std::lower_bound (
                        _xsd_LogLevelString_indexes_,
                        _xsd_LogLevelString_indexes_ + 6,
                        *this,
                        c));

      if (i == _xsd_LogLevelString_indexes_ + 6 || _xsd_LogLevelString_literals_[*i] != *this)
      {
        throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
      }

      return *i;
    }

    const char* const LogLevelString::
    _xsd_LogLevelString_literals_[6] =
    {
      "fatal",
      "error",
      "warn",
      "info",
      "debug",
      "trace"
    };

    const LogLevelString::Value LogLevelString::
    _xsd_LogLevelString_indexes_[6] =
    {
      ::fews::PI::LogLevelString::debug,
      ::fews::PI::LogLevelString::error,
      ::fews::PI::LogLevelString::fatal,
      ::fews::PI::LogLevelString::info,
      ::fews::PI::LogLevelString::trace,
      ::fews::PI::LogLevelString::warn
    };
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace fews
{
  namespace PI
  {
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (const ::std::string& u,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      ::std::auto_ptr< ::fews::PI::RunComplexType > r (
        ::fews::PI::parseRun (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (const ::std::string& u,
              ::xml_schema::ErrorHandler& h,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      ::std::auto_ptr< ::fews::PI::RunComplexType > r (
        ::fews::PI::parseRun (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (const ::std::string& u,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          u, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      ::std::auto_ptr< ::fews::PI::RunComplexType > r (
        ::fews::PI::parseRun (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::fews::PI::parseRun (isrc, f, p);
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              ::xml_schema::ErrorHandler& h,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::fews::PI::parseRun (isrc, h, f, p);
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is);
      return ::fews::PI::parseRun (isrc, h, f, p);
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              const ::std::string& sid,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::fews::PI::parseRun (isrc, f, p);
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              const ::std::string& sid,
              ::xml_schema::ErrorHandler& h,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0,
        (f & ::xml_schema::Flags::keep_dom) == 0);

      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::fews::PI::parseRun (isrc, h, f, p);
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              const ::std::string& sid,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
      return ::fews::PI::parseRun (isrc, h, f, p);
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::xercesc::InputSource& i,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xsd::cxx::tree::error_handler< char > h;

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

      ::std::auto_ptr< ::fews::PI::RunComplexType > r (
        ::fews::PI::parseRun (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::xercesc::InputSource& i,
              ::xml_schema::ErrorHandler& h,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      ::std::auto_ptr< ::fews::PI::RunComplexType > r (
        ::fews::PI::parseRun (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::xercesc::InputSource& i,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::parse< char > (
          i, h, p, f));

      if (!d.get ())
        throw ::xsd::cxx::tree::parsing< char > ();

      ::std::auto_ptr< ::fews::PI::RunComplexType > r (
        ::fews::PI::parseRun (
          d, f | ::xml_schema::Flags::own_dom, p));

      return r;
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (const ::xercesc::DOMDocument& d,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties& p)
    {
      if (f & ::xml_schema::Flags::keep_dom)
      {
        ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
          static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

        ::std::auto_ptr< ::fews::PI::RunComplexType > r (
          ::fews::PI::parseRun (
            c, f | ::xml_schema::Flags::own_dom, p));

        return r;
      }

      const ::xercesc::DOMElement& e (*d.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "Run" &&
          n.namespace_ () == "http://www.wldelft.nl/fews/PI")
      {
        ::std::auto_ptr< ::fews::PI::RunComplexType > r (
          ::xsd::cxx::tree::traits< ::fews::PI::RunComplexType, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "Run",
        "http://www.wldelft.nl/fews/PI");
    }

    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
              ::xml_schema::Flags f,
              const ::xml_schema::Properties&)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
        ((f & ::xml_schema::Flags::keep_dom) &&
         !(f & ::xml_schema::Flags::own_dom))
        ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
        : 0);

      ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
      const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (f & ::xml_schema::Flags::keep_dom)
        doc.setUserData (::xml_schema::dom::treeNodeKey,
                         (c.get () ? &c : &d),
                         0);

      if (n.name () == "Run" &&
          n.namespace_ () == "http://www.wldelft.nl/fews/PI")
      {
        ::std::auto_ptr< ::fews::PI::RunComplexType > r (
          ::xsd::cxx::tree::traits< ::fews::PI::RunComplexType, char >::create (
            e, f, 0));
        return r;
      }

      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "Run",
        "http://www.wldelft.nl/fews/PI");
    }
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace fews
{
  namespace PI
  {
    void
    serializeRun (::std::ostream& o,
                  const ::fews::PI::RunComplexType& s,
                  const ::xml_schema::NamespaceInfomap& m,
                  const ::std::string& e,
                  ::xml_schema::Flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0);

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeRun (s, m, f));

      ::xsd::cxx::tree::error_handler< char > h;

      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
      }
    }

    void
    serializeRun (::std::ostream& o,
                  const ::fews::PI::RunComplexType& s,
                  ::xml_schema::ErrorHandler& h,
                  const ::xml_schema::NamespaceInfomap& m,
                  const ::std::string& e,
                  ::xml_schema::Flags f)
    {
      ::xsd::cxx::xml::auto_initializer i (
        (f & ::xml_schema::Flags::dont_initialize) == 0);

      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeRun (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    serializeRun (::std::ostream& o,
                  const ::fews::PI::RunComplexType& s,
                  ::xercesc::DOMErrorHandler& h,
                  const ::xml_schema::NamespaceInfomap& m,
                  const ::std::string& e,
                  ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeRun (s, m, f));
      ::xsd::cxx::xml::dom::ostream_format_target t (o);
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    serializeRun (::xercesc::XMLFormatTarget& t,
                  const ::fews::PI::RunComplexType& s,
                  const ::xml_schema::NamespaceInfomap& m,
                  const ::std::string& e,
                  ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeRun (s, m, f));

      ::xsd::cxx::tree::error_handler< char > h;

      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
      }
    }

    void
    serializeRun (::xercesc::XMLFormatTarget& t,
                  const ::fews::PI::RunComplexType& s,
                  ::xml_schema::ErrorHandler& h,
                  const ::xml_schema::NamespaceInfomap& m,
                  const ::std::string& e,
                  ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeRun (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    serializeRun (::xercesc::XMLFormatTarget& t,
                  const ::fews::PI::RunComplexType& s,
                  ::xercesc::DOMErrorHandler& h,
                  const ::xml_schema::NamespaceInfomap& m,
                  const ::std::string& e,
                  ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::fews::PI::serializeRun (s, m, f));
      if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
      {
        throw ::xsd::cxx::tree::serialization< char > ();
      }
    }

    void
    serializeRun (::xercesc::DOMDocument& d,
                  const ::fews::PI::RunComplexType& s,
                  ::xml_schema::Flags)
    {
      ::xercesc::DOMElement& e (*d.getDocumentElement ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (e));

      if (n.name () == "Run" &&
          n.namespace_ () == "http://www.wldelft.nl/fews/PI")
      {
        e << s;
      }
      else
      {
        throw ::xsd::cxx::tree::unexpected_element < char > (
          n.name (),
          n.namespace_ (),
          "Run",
          "http://www.wldelft.nl/fews/PI");
      }
    }

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
    serializeRun (const ::fews::PI::RunComplexType& s,
                  const ::xml_schema::NamespaceInfomap& m,
                  ::xml_schema::Flags f)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
        ::xsd::cxx::xml::dom::serialize< char > (
          "Run",
          "http://www.wldelft.nl/fews/PI",
          m, f));

      ::fews::PI::serializeRun (*d, s, f);
      return d;
    }

    void
    operator<< (::xercesc::DOMElement& e, const RunComplexType& i)
    {
      e << static_cast< const ::xml_schema::Type& > (i);

      // logLevel
      //
      if (i.getLogLevel ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "logLevel",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getLogLevel ();
      }

      // timeZone
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "timeZone",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << i.getTimeZone ();
      }

      // startDateTime
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "startDateTime",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << i.getStartDateTime ();
      }

      // endDateTime
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "endDateTime",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << i.getEndDateTime ();
      }

      // time0
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "time0",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << i.getTime0 ();
      }

      // lastObservationDateTime
      //
      if (i.getLastObservationDateTime ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "lastObservationDateTime",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getLastObservationDateTime ();
      }

      // workDir
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "workDir",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << i.getWorkDir ();
      }

      // inputParameterFile
      //
      for (RunComplexType::InputParameterFileConstIterator
           b (i.getInputParameterFile ().begin ()), n (i.getInputParameterFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "inputParameterFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // inputStateDescriptionFile
      //
      for (RunComplexType::InputStateDescriptionFileConstIterator
           b (i.getInputStateDescriptionFile ().begin ()), n (i.getInputStateDescriptionFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "inputStateDescriptionFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // inputTimeSeriesFile
      //
      for (RunComplexType::InputTimeSeriesFileConstIterator
           b (i.getInputTimeSeriesFile ().begin ()), n (i.getInputTimeSeriesFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "inputTimeSeriesFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // inputMapStackFile
      //
      for (RunComplexType::InputMapStackFileConstIterator
           b (i.getInputMapStackFile ().begin ()), n (i.getInputMapStackFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "inputMapStackFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // inputNetcdfFile
      //
      for (RunComplexType::InputNetcdfFileConstIterator
           b (i.getInputNetcdfFile ().begin ()), n (i.getInputNetcdfFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "inputNetcdfFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // inputLongitudinalProfilesFile
      //
      for (RunComplexType::InputLongitudinalProfilesFileConstIterator
           b (i.getInputLongitudinalProfilesFile ().begin ()), n (i.getInputLongitudinalProfilesFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "inputLongitudinalProfilesFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // inputRatingCurveFile
      //
      for (RunComplexType::InputRatingCurveFileConstIterator
           b (i.getInputRatingCurveFile ().begin ()), n (i.getInputRatingCurveFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "inputRatingCurveFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // outputDiagnosticFile
      //
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "outputDiagnosticFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << i.getOutputDiagnosticFile ();
      }

      // outputStateDescriptionFile
      //
      if (i.getOutputStateDescriptionFile ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "outputStateDescriptionFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getOutputStateDescriptionFile ();
      }

      // outputTimeSeriesFile
      //
      for (RunComplexType::OutputTimeSeriesFileConstIterator
           b (i.getOutputTimeSeriesFile ().begin ()), n (i.getOutputTimeSeriesFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "outputTimeSeriesFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // outputMapStackFile
      //
      for (RunComplexType::OutputMapStackFileConstIterator
           b (i.getOutputMapStackFile ().begin ()), n (i.getOutputMapStackFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "outputMapStackFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // outputNetcdfFile
      //
      for (RunComplexType::OutputNetcdfFileConstIterator
           b (i.getOutputNetcdfFile ().begin ()), n (i.getOutputNetcdfFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "outputNetcdfFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // outputLongitudinalProfilesFile
      //
      for (RunComplexType::OutputLongitudinalProfilesFileConstIterator
           b (i.getOutputLongitudinalProfilesFile ().begin ()), n (i.getOutputLongitudinalProfilesFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "outputLongitudinalProfilesFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // outputCsvModuleRunTableFile
      //
      for (RunComplexType::OutputCsvModuleRunTableFileConstIterator
           b (i.getOutputCsvModuleRunTableFile ().begin ()), n (i.getOutputCsvModuleRunTableFile ().end ());
           b != n; ++b)
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "outputCsvModuleRunTableFile",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *b;
      }

      // properties
      //
      if (i.getProperties ())
      {
        ::xercesc::DOMElement& s (
          ::xsd::cxx::xml::dom::create_element (
            "properties",
            "http://www.wldelft.nl/fews/PI",
            e));

        s << *i.getProperties ();
      }

      // version
      //
      {
        ::xercesc::DOMAttr& a (
          ::xsd::cxx::xml::dom::create_attribute (
            "version",
            e));

        a << i.getVersion ();
      }
    }

    void
    operator<< (::xercesc::DOMElement& e, const LogLevelString& i)
    {
      e << static_cast< const ::xml_schema::String& > (i);
    }

    void
    operator<< (::xercesc::DOMAttr& a, const LogLevelString& i)
    {
      a << static_cast< const ::xml_schema::String& > (i);
    }

    void
    operator<< (::xml_schema::ListStream& l,
                const LogLevelString& i)
    {
      l << static_cast< const ::xml_schema::String& > (i);
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

