// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

/**
 * @file
 * @brief Generated from pi_run.xsd.
 */

#ifndef PI_RUN_HXX
#define PI_RUN_HXX

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 3030000L)
#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

#include <xsd/cxx/xml/char-lcp.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

#include <xsd/cxx/xml/dom/serialization-header.hxx>
#include <xsd/cxx/tree/serialization.hxx>
#include <xsd/cxx/tree/serialization/byte.hxx>
#include <xsd/cxx/tree/serialization/unsigned-byte.hxx>
#include <xsd/cxx/tree/serialization/short.hxx>
#include <xsd/cxx/tree/serialization/unsigned-short.hxx>
#include <xsd/cxx/tree/serialization/int.hxx>
#include <xsd/cxx/tree/serialization/unsigned-int.hxx>
#include <xsd/cxx/tree/serialization/long.hxx>
#include <xsd/cxx/tree/serialization/unsigned-long.hxx>
#include <xsd/cxx/tree/serialization/boolean.hxx>
#include <xsd/cxx/tree/serialization/float.hxx>
#include <xsd/cxx/tree/serialization/double.hxx>
#include <xsd/cxx/tree/serialization/decimal.hxx>

/**
 * @brief C++ namespace for the %http://www.w3.org/2001/XMLSchema
 * schema namespace.
 */
namespace xml_schema
{
  // anyType and anySimpleType.
  //

  /**
   * @brief C++ type corresponding to the anyType XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::type Type;

  /**
   * @brief C++ type corresponding to the anySimpleType XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::simple_type< Type > SimpleType;

  /**
   * @brief Alias for the anyType type.
   */
  typedef ::xsd::cxx::tree::type Container;


  // 8-bit
  //

  /**
   * @brief C++ type corresponding to the byte XML Schema
   * built-in type.
   */
  typedef signed char Byte;

  /**
   * @brief C++ type corresponding to the unsignedByte XML Schema
   * built-in type.
   */
  typedef unsigned char UnsignedByte;


  // 16-bit
  //

  /**
   * @brief C++ type corresponding to the short XML Schema
   * built-in type.
   */
  typedef short Short;

  /**
   * @brief C++ type corresponding to the unsignedShort XML Schema
   * built-in type.
   */
  typedef unsigned short UnsignedShort;


  // 32-bit
  //

  /**
   * @brief C++ type corresponding to the int XML Schema
   * built-in type.
   */
  typedef int Int;

  /**
   * @brief C++ type corresponding to the unsignedInt XML Schema
   * built-in type.
   */
  typedef unsigned int UnsignedInt;


  // 64-bit
  //

  /**
   * @brief C++ type corresponding to the long XML Schema
   * built-in type.
   */
  typedef long long Long;

  /**
   * @brief C++ type corresponding to the unsignedLong XML Schema
   * built-in type.
   */
  typedef unsigned long long UnsignedLong;


  // Supposed to be arbitrary-length integral types.
  //

  /**
   * @brief C++ type corresponding to the integer XML Schema
   * built-in type.
   */
  typedef long long Integer;

  /**
   * @brief C++ type corresponding to the nonPositiveInteger XML Schema
   * built-in type.
   */
  typedef long long NonPositiveInteger;

  /**
   * @brief C++ type corresponding to the nonNegativeInteger XML Schema
   * built-in type.
   */
  typedef unsigned long long NonNegativeInteger;

  /**
   * @brief C++ type corresponding to the positiveInteger XML Schema
   * built-in type.
   */
  typedef unsigned long long PositiveInteger;

  /**
   * @brief C++ type corresponding to the negativeInteger XML Schema
   * built-in type.
   */
  typedef long long NegativeInteger;


  // Boolean.
  //

  /**
   * @brief C++ type corresponding to the boolean XML Schema
   * built-in type.
   */
  typedef bool Boolean;


  // Floating-point types.
  //

  /**
   * @brief C++ type corresponding to the float XML Schema
   * built-in type.
   */
  typedef float Float;

  /**
   * @brief C++ type corresponding to the double XML Schema
   * built-in type.
   */
  typedef double Double;

  /**
   * @brief C++ type corresponding to the decimal XML Schema
   * built-in type.
   */
  typedef double Decimal;


  // String types.
  //

  /**
   * @brief C++ type corresponding to the string XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::string< char, SimpleType > String;

  /**
   * @brief C++ type corresponding to the normalizedString XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::normalized_string< char, String > NormalizedString;

  /**
   * @brief C++ type corresponding to the token XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::token< char, NormalizedString > Token;

  /**
   * @brief C++ type corresponding to the Name XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::name< char, Token > Name;

  /**
   * @brief C++ type corresponding to the NMTOKEN XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::nmtoken< char, Token > Nmtoken;

  /**
   * @brief C++ type corresponding to the NMTOKENS XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::nmtokens< char, SimpleType, Nmtoken > Nmtokens;

  /**
   * @brief C++ type corresponding to the NCName XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::ncname< char, Name > Ncname;

  /**
   * @brief C++ type corresponding to the language XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::language< char, Token > Language;


  // ID/IDREF.
  //

  /**
   * @brief C++ type corresponding to the ID XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::id< char, Ncname > Id;

  /**
   * @brief C++ type corresponding to the IDREF XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::idref< char, Ncname, Type > Idref;

  /**
   * @brief C++ type corresponding to the IDREFS XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::idrefs< char, SimpleType, Idref > Idrefs;


  // URI.
  //

  /**
   * @brief C++ type corresponding to the anyURI XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::uri< char, SimpleType > Uri;


  // Qualified name.
  //

  /**
   * @brief C++ type corresponding to the QName XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::qname< char, SimpleType, Uri, Ncname > Qname;


  // Binary.
  //

  /**
   * @brief Binary buffer type.
   */
  typedef ::xsd::cxx::tree::buffer< char > Buffer;

  /**
   * @brief C++ type corresponding to the base64Binary XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::base64_binary< char, SimpleType > Base64Binary;

  /**
   * @brief C++ type corresponding to the hexBinary XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::hex_binary< char, SimpleType > HexBinary;


  // Date/time.
  //

  /**
   * @brief Time zone type.
   */
  typedef ::xsd::cxx::tree::time_zone TimeZone;

  /**
   * @brief C++ type corresponding to the date XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::date< char, SimpleType > Date;

  /**
   * @brief C++ type corresponding to the dateTime XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::date_time< char, SimpleType > DateTime;

  /**
   * @brief C++ type corresponding to the duration XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::duration< char, SimpleType > Duration;

  /**
   * @brief C++ type corresponding to the gDay XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::gday< char, SimpleType > Gday;

  /**
   * @brief C++ type corresponding to the gMonth XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::gmonth< char, SimpleType > Gmonth;

  /**
   * @brief C++ type corresponding to the gMonthDay XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::gmonth_day< char, SimpleType > GmonthDay;

  /**
   * @brief C++ type corresponding to the gYear XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::gyear< char, SimpleType > Gyear;

  /**
   * @brief C++ type corresponding to the gYearMonth XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::gyear_month< char, SimpleType > GyearMonth;

  /**
   * @brief C++ type corresponding to the time XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::time< char, SimpleType > Time;


  // Entity.
  //

  /**
   * @brief C++ type corresponding to the ENTITY XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::entity< char, Ncname > Entity;

  /**
   * @brief C++ type corresponding to the ENTITIES XML Schema
   * built-in type.
   */
  typedef ::xsd::cxx::tree::entities< char, SimpleType, Entity > Entities;


  // Namespace information and list stream. Used in
  // serialization functions.
  //
  /**
   * @brief Namespace serialization information.
   */
  typedef ::xsd::cxx::xml::dom::namespace_info< char > NamespaceInfo;

  /**
   * @brief Namespace serialization information map.
   */
  typedef ::xsd::cxx::xml::dom::namespace_infomap< char > NamespaceInfomap;

  /**
   * @brief List serialization stream.
   */
  typedef ::xsd::cxx::tree::list_stream< char > ListStream;

  /**
   * @brief Serialization wrapper for the %double type.
   */
  typedef ::xsd::cxx::tree::as_double< Double > AsDouble;

  /**
   * @brief Serialization wrapper for the %decimal type.
   */
  typedef ::xsd::cxx::tree::as_decimal< Decimal > AsDecimal;

  /**
   * @brief Simple type facet.
   */
  typedef ::xsd::cxx::tree::facet Facet;

  // Flags and properties.
  //

  /**
   * @brief Parsing and serialization flags.
   */
  typedef ::xsd::cxx::tree::flags Flags;

  /**
   * @brief Parsing properties.
   */
  typedef ::xsd::cxx::tree::properties< char > Properties;

  // Parsing/serialization diagnostics.
  //

  /**
   * @brief Error severity.
   */
  typedef ::xsd::cxx::tree::severity Severity;

  /**
   * @brief Error condition.
   */
  typedef ::xsd::cxx::tree::error< char > Error;

  /**
   * @brief List of %error conditions.
   */
  typedef ::xsd::cxx::tree::diagnostics< char > Diagnostics;

  // Exceptions.
  //

  /**
   * @brief Root of the C++/Tree %exception hierarchy.
   */
  typedef ::xsd::cxx::tree::exception< char > Exception;

  /**
   * @brief Exception indicating that the size argument exceeds
   * the capacity argument.
   */
  typedef ::xsd::cxx::tree::bounds< char > Bounds;

  /**
   * @brief Exception indicating that a duplicate ID value
   * was encountered in the object model.
   */
  typedef ::xsd::cxx::tree::duplicate_id< char > DuplicateId;

  /**
   * @brief Exception indicating a parsing failure.
   */
  typedef ::xsd::cxx::tree::parsing< char > Parsing;

  /**
   * @brief Exception indicating that an expected element
   * was not encountered.
   */
  typedef ::xsd::cxx::tree::expected_element< char > ExpectedElement;

  /**
   * @brief Exception indicating that an unexpected element
   * was encountered.
   */
  typedef ::xsd::cxx::tree::unexpected_element< char > UnexpectedElement;

  /**
   * @brief Exception indicating that an expected attribute
   * was not encountered.
   */
  typedef ::xsd::cxx::tree::expected_attribute< char > ExpectedAttribute;

  /**
   * @brief Exception indicating that an unexpected enumerator
   * was encountered.
   */
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > UnexpectedEnumerator;

  /**
   * @brief Exception indicating that the text content was
   * expected for an element.
   */
  typedef ::xsd::cxx::tree::expected_text_content< char > ExpectedTextContent;

  /**
   * @brief Exception indicating that a prefix-namespace
   * mapping was not provided.
   */
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > NoPrefixMapping;

  /**
   * @brief Exception indicating a serialization failure.
   */
  typedef ::xsd::cxx::tree::serialization< char > Serialization;

  /**
   * @brief Error handler callback interface.
   */
  typedef ::xsd::cxx::xml::error_handler< char > ErrorHandler;

  /**
   * @brief DOM interaction.
   */
  namespace dom
  {
    /**
     * @brief Automatic pointer for DOMDocument.
     */
    using ::xsd::cxx::xml::dom::auto_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    /**
     * @brief DOM user data key for back pointers to tree nodes.
     */
    const XMLCh* const treeNodeKey = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
namespace fews
{
  namespace PI
  {
    class RunComplexType;
    class LogLevelString;
  }
}


#include <memory>    // std::auto_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search

#include <xsd/cxx/xml/char-lcp.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

#include "pi_sharedtypes.hxx"

namespace fews
{
  /**
   * @brief C++ namespace for the %http://www.wldelft.nl/fews/PI
   * schema namespace.
   */
  namespace PI
  {
    /**
     * @brief Class corresponding to the %RunComplexType schema type.
     *
     * @nosubgrouping
     */
    class RunComplexType: public ::xml_schema::Type
    {
      public:
      /**
       * @name logLevel
       *
       * @brief Accessor and modifier functions for the %logLevel
       * optional element.
       *
       * since 1.8, Log level compatible with log4j.
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::fews::PI::LogLevelString LogLevelType;

      /**
       * @brief Element optional container type.
       */
      typedef ::xsd::cxx::tree::optional< LogLevelType > LogLevelOptional;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< LogLevelType, char > LogLevelTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * container.
       *
       * @return A constant reference to the optional container.
       */
      const LogLevelOptional&
      getLogLevel () const;

      /**
       * @brief Return a read-write reference to the element container.
       *
       * @return A reference to the optional container.
       */
      LogLevelOptional&
      getLogLevel ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setLogLevel (const LogLevelType& x);

      /**
       * @brief Set the element value.
       *
       * @param x An optional container with the new value to set.
       *
       * If the value is present in @a x then this function makes a copy 
       * of this value and sets it as the new value of the element.
       * Otherwise the element container is set the 'not present' state.
       */
      void
      setLogLevel (const LogLevelOptional& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly instead
       * of making a copy.
       */
      void
      setLogLevel (::std::auto_ptr< LogLevelType > p);

      //@}

      /**
       * @name timeZone
       *
       * @brief Accessor and modifier functions for the %timeZone
       * required element.
       *
       * Time zone used in the exported pi files. This is also the default time
       * zone used by the general adapter
       * when the time zone is not specified in an imported output file
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::fews::PI::TimeZoneSimpleType TimeZoneType;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< TimeZoneType, char > TimeZoneTraits;

      /**
       * @brief Return a read-only (constant) reference to the element.
       *
       * @return A constant reference to the element.
       */
      const TimeZoneType&
      getTimeZone () const;

      /**
       * @brief Return a read-write reference to the element.
       *
       * @return A reference to the element.
       */
      TimeZoneType&
      getTimeZone ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setTimeZone (const TimeZoneType& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly
       * instead of making a copy.
       */
      void
      setTimeZone (::std::auto_ptr< TimeZoneType > p);

      //@}

      /**
       * @name startDateTime
       *
       * @brief Accessor and modifier functions for the %startDateTime
       * required element.
       *
       * Start of the run. The time of the of the state exported by the General
       * Adapter. When there is no state exported the earliest time in any time
       * series exported by the General Adapter will be used
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::fews::PI::DateTimeComplexType StartDateTimeType;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< StartDateTimeType, char > StartDateTimeTraits;

      /**
       * @brief Return a read-only (constant) reference to the element.
       *
       * @return A constant reference to the element.
       */
      const StartDateTimeType&
      getStartDateTime () const;

      /**
       * @brief Return a read-write reference to the element.
       *
       * @return A reference to the element.
       */
      StartDateTimeType&
      getStartDateTime ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setStartDateTime (const StartDateTimeType& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly
       * instead of making a copy.
       */
      void
      setStartDateTime (::std::auto_ptr< StartDateTimeType > p);

      //@}

      /**
       * @name endDateTime
       *
       * @brief Accessor and modifier functions for the %endDateTime
       * required element.
       *
       * End of the run. The latest time exported by the General Adapter
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::fews::PI::DateTimeComplexType EndDateTimeType;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< EndDateTimeType, char > EndDateTimeTraits;

      /**
       * @brief Return a read-only (constant) reference to the element.
       *
       * @return A constant reference to the element.
       */
      const EndDateTimeType&
      getEndDateTime () const;

      /**
       * @brief Return a read-write reference to the element.
       *
       * @return A reference to the element.
       */
      EndDateTimeType&
      getEndDateTime ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setEndDateTime (const EndDateTimeType& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly
       * instead of making a copy.
       */
      void
      setEndDateTime (::std::auto_ptr< EndDateTimeType > p);

      //@}

      /**
       * @name time0
       *
       * @brief Accessor and modifier functions for the %time0
       * required element.
       *
       * This is the start of a forecast for a forecast run
       * This is the time 0 of a FEWS task run.
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::fews::PI::DateTimeComplexType Time0Type;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< Time0Type, char > Time0Traits;

      /**
       * @brief Return a read-only (constant) reference to the element.
       *
       * @return A constant reference to the element.
       */
      const Time0Type&
      getTime0 () const;

      /**
       * @brief Return a read-write reference to the element.
       *
       * @return A reference to the element.
       */
      Time0Type&
      getTime0 ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setTime0 (const Time0Type& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly
       * instead of making a copy.
       */
      void
      setTime0 (::std::auto_ptr< Time0Type > p);

      //@}

      /**
       * @name lastObservationDateTime
       *
       * @brief Accessor and modifier functions for the %lastObservationDateTime
       * optional element.
       *
       * Last time of non missing observation based on observed time series
       * sets configured in the General Adapter.
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::fews::PI::DateTimeComplexType LastObservationDateTimeType;

      /**
       * @brief Element optional container type.
       */
      typedef ::xsd::cxx::tree::optional< LastObservationDateTimeType > LastObservationDateTimeOptional;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< LastObservationDateTimeType, char > LastObservationDateTimeTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * container.
       *
       * @return A constant reference to the optional container.
       */
      const LastObservationDateTimeOptional&
      getLastObservationDateTime () const;

      /**
       * @brief Return a read-write reference to the element container.
       *
       * @return A reference to the optional container.
       */
      LastObservationDateTimeOptional&
      getLastObservationDateTime ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setLastObservationDateTime (const LastObservationDateTimeType& x);

      /**
       * @brief Set the element value.
       *
       * @param x An optional container with the new value to set.
       *
       * If the value is present in @a x then this function makes a copy 
       * of this value and sets it as the new value of the element.
       * Otherwise the element container is set the 'not present' state.
       */
      void
      setLastObservationDateTime (const LastObservationDateTimeOptional& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly instead
       * of making a copy.
       */
      void
      setLastObservationDateTime (::std::auto_ptr< LastObservationDateTimeType > p);

      //@}

      /**
       * @name workDir
       *
       * @brief Accessor and modifier functions for the %workDir
       * required element.
       *
       * Fully qualified path to the current working directory.
       * This is also the startup directory of an non java executable launched
       * by the general adapter.
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String WorkDirType;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< WorkDirType, char > WorkDirTraits;

      /**
       * @brief Return a read-only (constant) reference to the element.
       *
       * @return A constant reference to the element.
       */
      const WorkDirType&
      getWorkDir () const;

      /**
       * @brief Return a read-write reference to the element.
       *
       * @return A reference to the element.
       */
      WorkDirType&
      getWorkDir ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setWorkDir (const WorkDirType& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly
       * instead of making a copy.
       */
      void
      setWorkDir (::std::auto_ptr< WorkDirType > p);

      //@}

      /**
       * @name inputParameterFile
       *
       * @brief Accessor and modifier functions for the %inputParameterFile
       * sequence element.
       *
       * Fully qualified path to the pi parameter file exported by the
       * General Adapter before the run.
       * An active modifier is already applied to this file
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String InputParameterFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< InputParameterFileType > InputParameterFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef InputParameterFileSequence::iterator InputParameterFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef InputParameterFileSequence::const_iterator InputParameterFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< InputParameterFileType, char > InputParameterFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const InputParameterFileSequence&
      getInputParameterFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      InputParameterFileSequence&
      getInputParameterFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setInputParameterFile (const InputParameterFileSequence& s);

      //@}

      /**
       * @name inputStateDescriptionFile
       *
       * @brief Accessor and modifier functions for the %inputStateDescriptionFile
       * sequence element.
       *
       * Fully qualified path to the pi state file that describes the state
       * exported by the General Adapter before the run.
       * In this file you can also find the state time and the paths to the
       * actual state files
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String InputStateDescriptionFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< InputStateDescriptionFileType > InputStateDescriptionFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef InputStateDescriptionFileSequence::iterator InputStateDescriptionFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef InputStateDescriptionFileSequence::const_iterator InputStateDescriptionFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< InputStateDescriptionFileType, char > InputStateDescriptionFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const InputStateDescriptionFileSequence&
      getInputStateDescriptionFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      InputStateDescriptionFileSequence&
      getInputStateDescriptionFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setInputStateDescriptionFile (const InputStateDescriptionFileSequence& s);

      //@}

      /**
       * @name inputTimeSeriesFile
       *
       * @brief Accessor and modifier functions for the %inputTimeSeriesFile
       * sequence element.
       *
       * Fully qualified path to a pi time series file exported by the General
       * Adapter before the run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String InputTimeSeriesFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< InputTimeSeriesFileType > InputTimeSeriesFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef InputTimeSeriesFileSequence::iterator InputTimeSeriesFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef InputTimeSeriesFileSequence::const_iterator InputTimeSeriesFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< InputTimeSeriesFileType, char > InputTimeSeriesFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const InputTimeSeriesFileSequence&
      getInputTimeSeriesFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      InputTimeSeriesFileSequence&
      getInputTimeSeriesFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setInputTimeSeriesFile (const InputTimeSeriesFileSequence& s);

      //@}

      /**
       * @name inputMapStackFile
       *
       * @brief Accessor and modifier functions for the %inputMapStackFile
       * sequence element.
       *
       * Fully qualified path to a map stack file exported by the General
       * Adapter before the run.
       * A map stack is a list of raster files for each time step.
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String InputMapStackFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< InputMapStackFileType > InputMapStackFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef InputMapStackFileSequence::iterator InputMapStackFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef InputMapStackFileSequence::const_iterator InputMapStackFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< InputMapStackFileType, char > InputMapStackFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const InputMapStackFileSequence&
      getInputMapStackFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      InputMapStackFileSequence&
      getInputMapStackFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setInputMapStackFile (const InputMapStackFileSequence& s);

      //@}

      /**
       * @name inputNetcdfFile
       *
       * @brief Accessor and modifier functions for the %inputNetcdfFile
       * sequence element.
       *
       * Fully qualified path to a pi netcdf file exported by the General
       * Adapter before the run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String InputNetcdfFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< InputNetcdfFileType > InputNetcdfFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef InputNetcdfFileSequence::iterator InputNetcdfFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef InputNetcdfFileSequence::const_iterator InputNetcdfFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< InputNetcdfFileType, char > InputNetcdfFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const InputNetcdfFileSequence&
      getInputNetcdfFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      InputNetcdfFileSequence&
      getInputNetcdfFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setInputNetcdfFile (const InputNetcdfFileSequence& s);

      //@}

      /**
       * @name inputLongitudinalProfilesFile
       *
       * @brief Accessor and modifier functions for the %inputLongitudinalProfilesFile
       * sequence element.
       *
       * Fully qualified path to a pi longitudinal profiles file exported by
       * the General before the run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String InputLongitudinalProfilesFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< InputLongitudinalProfilesFileType > InputLongitudinalProfilesFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef InputLongitudinalProfilesFileSequence::iterator InputLongitudinalProfilesFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef InputLongitudinalProfilesFileSequence::const_iterator InputLongitudinalProfilesFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< InputLongitudinalProfilesFileType, char > InputLongitudinalProfilesFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const InputLongitudinalProfilesFileSequence&
      getInputLongitudinalProfilesFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      InputLongitudinalProfilesFileSequence&
      getInputLongitudinalProfilesFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setInputLongitudinalProfilesFile (const InputLongitudinalProfilesFileSequence& s);

      //@}

      /**
       * @name inputRatingCurveFile
       *
       * @brief Accessor and modifier functions for the %inputRatingCurveFile
       * sequence element.
       *
       * Fully qualified path to a pi_ratingcurves file exported by the General
       * Adapter before the model run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String InputRatingCurveFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< InputRatingCurveFileType > InputRatingCurveFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef InputRatingCurveFileSequence::iterator InputRatingCurveFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef InputRatingCurveFileSequence::const_iterator InputRatingCurveFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< InputRatingCurveFileType, char > InputRatingCurveFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const InputRatingCurveFileSequence&
      getInputRatingCurveFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      InputRatingCurveFileSequence&
      getInputRatingCurveFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setInputRatingCurveFile (const InputRatingCurveFileSequence& s);

      //@}

      /**
       * @name outputDiagnosticFile
       *
       * @brief Accessor and modifier functions for the %outputDiagnosticFile
       * required element.
       *
       * Fully qualified path to a pi diagnostic file that that will be
       * imported by the General
       * Adapter after the run	. It is deleted by the general adapter before
       * the run.
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String OutputDiagnosticFileType;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< OutputDiagnosticFileType, char > OutputDiagnosticFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element.
       *
       * @return A constant reference to the element.
       */
      const OutputDiagnosticFileType&
      getOutputDiagnosticFile () const;

      /**
       * @brief Return a read-write reference to the element.
       *
       * @return A reference to the element.
       */
      OutputDiagnosticFileType&
      getOutputDiagnosticFile ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setOutputDiagnosticFile (const OutputDiagnosticFileType& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly
       * instead of making a copy.
       */
      void
      setOutputDiagnosticFile (::std::auto_ptr< OutputDiagnosticFileType > p);

      //@}

      /**
       * @name outputStateDescriptionFile
       *
       * @brief Accessor and modifier functions for the %outputStateDescriptionFile
       * optional element.
       *
       * Fully qualified path to the pi state file that describes the state
       * that will be imported by the General Adapter
       * adapter after the run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String OutputStateDescriptionFileType;

      /**
       * @brief Element optional container type.
       */
      typedef ::xsd::cxx::tree::optional< OutputStateDescriptionFileType > OutputStateDescriptionFileOptional;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< OutputStateDescriptionFileType, char > OutputStateDescriptionFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * container.
       *
       * @return A constant reference to the optional container.
       */
      const OutputStateDescriptionFileOptional&
      getOutputStateDescriptionFile () const;

      /**
       * @brief Return a read-write reference to the element container.
       *
       * @return A reference to the optional container.
       */
      OutputStateDescriptionFileOptional&
      getOutputStateDescriptionFile ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setOutputStateDescriptionFile (const OutputStateDescriptionFileType& x);

      /**
       * @brief Set the element value.
       *
       * @param x An optional container with the new value to set.
       *
       * If the value is present in @a x then this function makes a copy 
       * of this value and sets it as the new value of the element.
       * Otherwise the element container is set the 'not present' state.
       */
      void
      setOutputStateDescriptionFile (const OutputStateDescriptionFileOptional& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly instead
       * of making a copy.
       */
      void
      setOutputStateDescriptionFile (::std::auto_ptr< OutputStateDescriptionFileType > p);

      //@}

      /**
       * @name outputTimeSeriesFile
       *
       * @brief Accessor and modifier functions for the %outputTimeSeriesFile
       * sequence element.
       *
       * Fully qualified path to a pi time series file that will be imported by
       * the General Adapter after the run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String OutputTimeSeriesFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< OutputTimeSeriesFileType > OutputTimeSeriesFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef OutputTimeSeriesFileSequence::iterator OutputTimeSeriesFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef OutputTimeSeriesFileSequence::const_iterator OutputTimeSeriesFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< OutputTimeSeriesFileType, char > OutputTimeSeriesFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const OutputTimeSeriesFileSequence&
      getOutputTimeSeriesFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      OutputTimeSeriesFileSequence&
      getOutputTimeSeriesFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setOutputTimeSeriesFile (const OutputTimeSeriesFileSequence& s);

      //@}

      /**
       * @name outputMapStackFile
       *
       * @brief Accessor and modifier functions for the %outputMapStackFile
       * sequence element.
       *
       * Fully qualified path to a pi map stack file that will be imported by
       * the General
       * Adapter after the run. A map stack is a list of raster files for each
       * time step.
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String OutputMapStackFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< OutputMapStackFileType > OutputMapStackFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef OutputMapStackFileSequence::iterator OutputMapStackFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef OutputMapStackFileSequence::const_iterator OutputMapStackFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< OutputMapStackFileType, char > OutputMapStackFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const OutputMapStackFileSequence&
      getOutputMapStackFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      OutputMapStackFileSequence&
      getOutputMapStackFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setOutputMapStackFile (const OutputMapStackFileSequence& s);

      //@}

      /**
       * @name outputNetcdfFile
       *
       * @brief Accessor and modifier functions for the %outputNetcdfFile
       * sequence element.
       *
       * Fully qualified path to a pi netcdf file that will be imported by the
       * General
       * Adapter after the run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String OutputNetcdfFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< OutputNetcdfFileType > OutputNetcdfFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef OutputNetcdfFileSequence::iterator OutputNetcdfFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef OutputNetcdfFileSequence::const_iterator OutputNetcdfFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< OutputNetcdfFileType, char > OutputNetcdfFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const OutputNetcdfFileSequence&
      getOutputNetcdfFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      OutputNetcdfFileSequence&
      getOutputNetcdfFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setOutputNetcdfFile (const OutputNetcdfFileSequence& s);

      //@}

      /**
       * @name outputLongitudinalProfilesFile
       *
       * @brief Accessor and modifier functions for the %outputLongitudinalProfilesFile
       * sequence element.
       *
       * Fully qualified path to a pi longitudinal profiles file that will be
       * imported by the General
       * Adapter after the run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String OutputLongitudinalProfilesFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< OutputLongitudinalProfilesFileType > OutputLongitudinalProfilesFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef OutputLongitudinalProfilesFileSequence::iterator OutputLongitudinalProfilesFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef OutputLongitudinalProfilesFileSequence::const_iterator OutputLongitudinalProfilesFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< OutputLongitudinalProfilesFileType, char > OutputLongitudinalProfilesFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const OutputLongitudinalProfilesFileSequence&
      getOutputLongitudinalProfilesFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      OutputLongitudinalProfilesFileSequence&
      getOutputLongitudinalProfilesFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setOutputLongitudinalProfilesFile (const OutputLongitudinalProfilesFileSequence& s);

      //@}

      /**
       * @name outputCsvModuleRunTableFile
       *
       * @brief Accessor and modifier functions for the %outputCsvModuleRunTableFile
       * sequence element.
       *
       * Fully qualified path to a csv module run table file that will be
       * imported by the General
       * Adapter after the run
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::xml_schema::String OutputCsvModuleRunTableFileType;

      /**
       * @brief Element sequence container type.
       */
      typedef ::xsd::cxx::tree::sequence< OutputCsvModuleRunTableFileType > OutputCsvModuleRunTableFileSequence;

      /**
       * @brief Element iterator type.
       */
      typedef OutputCsvModuleRunTableFileSequence::iterator OutputCsvModuleRunTableFileIterator;

      /**
       * @brief Element constant iterator type.
       */
      typedef OutputCsvModuleRunTableFileSequence::const_iterator OutputCsvModuleRunTableFileConstIterator;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< OutputCsvModuleRunTableFileType, char > OutputCsvModuleRunTableFileTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * sequence.
       *
       * @return A constant reference to the sequence container.
       */
      const OutputCsvModuleRunTableFileSequence&
      getOutputCsvModuleRunTableFile () const;

      /**
       * @brief Return a read-write reference to the element sequence.
       *
       * @return A reference to the sequence container.
       */
      OutputCsvModuleRunTableFileSequence&
      getOutputCsvModuleRunTableFile ();

      /**
       * @brief Copy elements from a given sequence.
       *
       * @param s A sequence to copy elements from.
       *
       * For each element in @a s this function makes a copy and adds it 
       * to the sequence. Note that this operation completely changes the 
       * sequence and all old elements will be lost.
       */
      void
      setOutputCsvModuleRunTableFile (const OutputCsvModuleRunTableFileSequence& s);

      //@}

      /**
       * @name properties
       *
       * @brief Accessor and modifier functions for the %properties
       * optional element.
       *
       * Kind of an extra command line argument for the pre and post adapter.
       * This is also a
       * convenient way way to pass global properties to a pre or post adapter.
       * An adapter is not allowed to access the
       * FEWS global.properties directly.
       * These extra options makes an additional pre or post adapter
       * configuration file unnecessary.
       * See the documentation of the used pre and post adapter for the
       * supported property keys with their allowed values
       */
      //@{

      /**
       * @brief Element type.
       */
      typedef ::fews::PI::PropertiesComplexType PropertiesType;

      /**
       * @brief Element optional container type.
       */
      typedef ::xsd::cxx::tree::optional< PropertiesType > PropertiesOptional;

      /**
       * @brief Element traits type.
       */
      typedef ::xsd::cxx::tree::traits< PropertiesType, char > PropertiesTraits;

      /**
       * @brief Return a read-only (constant) reference to the element
       * container.
       *
       * @return A constant reference to the optional container.
       */
      const PropertiesOptional&
      getProperties () const;

      /**
       * @brief Return a read-write reference to the element container.
       *
       * @return A reference to the optional container.
       */
      PropertiesOptional&
      getProperties ();

      /**
       * @brief Set the element value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the element.
       */
      void
      setProperties (const PropertiesType& x);

      /**
       * @brief Set the element value.
       *
       * @param x An optional container with the new value to set.
       *
       * If the value is present in @a x then this function makes a copy 
       * of this value and sets it as the new value of the element.
       * Otherwise the element container is set the 'not present' state.
       */
      void
      setProperties (const PropertiesOptional& x);

      /**
       * @brief Set the element value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly instead
       * of making a copy.
       */
      void
      setProperties (::std::auto_ptr< PropertiesType > p);

      //@}

      /**
       * @name version
       *
       * @brief Accessor and modifier functions for the %version
       * required attribute.
       */
      //@{

      /**
       * @brief Attribute type.
       */
      typedef ::fews::PI::VersionString VersionType;

      /**
       * @brief Attribute traits type.
       */
      typedef ::xsd::cxx::tree::traits< VersionType, char > VersionTraits;

      /**
       * @brief Return a read-only (constant) reference to the attribute.
       *
       * @return A constant reference to the attribute.
       */
      const VersionType&
      getVersion () const;

      /**
       * @brief Return a read-write reference to the attribute.
       *
       * @return A reference to the attribute.
       */
      VersionType&
      getVersion ();

      /**
       * @brief Set the attribute value.
       *
       * @param x A new value to set.
       *
       * This function makes a copy of its argument and sets it as
       * the new value of the attribute.
       */
      void
      setVersion (const VersionType& x);

      /**
       * @brief Set the attribute value without copying.
       *
       * @param p A new value to use.
       *
       * This function will try to use the passed value directly
       * instead of making a copy.
       */
      void
      setVersion (::std::auto_ptr< VersionType > p);

      //@}

      /**
       * @name Constructors
       */
      //@{

      /**
       * @brief Create an instance from the ultimate base and
       * initializers for required elements and attributes.
       */
      RunComplexType (const TimeZoneType&,
                      const StartDateTimeType&,
                      const EndDateTimeType&,
                      const Time0Type&,
                      const WorkDirType&,
                      const OutputDiagnosticFileType&,
                      const VersionType&);

      /**
       * @brief Create an instance from the ultimate base and
       * initializers for required elements and attributes
       * (auto_ptr version).
       *
       * This constructor will try to use the passed values directly
       * instead of making copies.
       */
      RunComplexType (const TimeZoneType&,
                      ::std::auto_ptr< StartDateTimeType >&,
                      ::std::auto_ptr< EndDateTimeType >&,
                      ::std::auto_ptr< Time0Type >&,
                      const WorkDirType&,
                      const OutputDiagnosticFileType&,
                      const VersionType&);

      /**
       * @brief Create an instance from a DOM element.
       *
       * @param e A DOM element to extract the data from.
       * @param f Flags to create the new instance with.
       * @param c A pointer to the object that will contain the new
       * instance.
       */
      RunComplexType (const ::xercesc::DOMElement& e,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

      /**
       * @brief Copy constructor.
       *
       * @param x An instance to make a copy of.
       * @param f Flags to create the copy with.
       * @param c A pointer to the object that will contain the copy.
       *
       * For polymorphic object models use the @c _clone function instead.
       */
      RunComplexType (const RunComplexType& x,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

      /**
       * @brief Copy the instance polymorphically.
       *
       * @param f Flags to create the copy with.
       * @param c A pointer to the object that will contain the copy.
       * @return A pointer to the dynamically allocated copy.
       *
       * This function ensures that the dynamic type of the instance is
       * used for copying and should be used for polymorphic object
       * models instead of the copy constructor.
       */
      virtual RunComplexType*
      _clone (::xml_schema::Flags f = 0,
              ::xml_schema::Container* c = 0) const;

      //@}

      /**
       * @brief Destructor.
       */
      virtual 
      ~RunComplexType ();

      // Implementation.
      //

      //@cond

      protected:
      void
      parse (::xsd::cxx::xml::dom::parser< char >&,
             ::xml_schema::Flags);

      protected:
      LogLevelOptional logLevel_;
      ::xsd::cxx::tree::one< TimeZoneType > timeZone_;
      ::xsd::cxx::tree::one< StartDateTimeType > startDateTime_;
      ::xsd::cxx::tree::one< EndDateTimeType > endDateTime_;
      ::xsd::cxx::tree::one< Time0Type > time0_;
      LastObservationDateTimeOptional lastObservationDateTime_;
      ::xsd::cxx::tree::one< WorkDirType > workDir_;
      InputParameterFileSequence inputParameterFile_;
      InputStateDescriptionFileSequence inputStateDescriptionFile_;
      InputTimeSeriesFileSequence inputTimeSeriesFile_;
      InputMapStackFileSequence inputMapStackFile_;
      InputNetcdfFileSequence inputNetcdfFile_;
      InputLongitudinalProfilesFileSequence inputLongitudinalProfilesFile_;
      InputRatingCurveFileSequence inputRatingCurveFile_;
      ::xsd::cxx::tree::one< OutputDiagnosticFileType > outputDiagnosticFile_;
      OutputStateDescriptionFileOptional outputStateDescriptionFile_;
      OutputTimeSeriesFileSequence outputTimeSeriesFile_;
      OutputMapStackFileSequence outputMapStackFile_;
      OutputNetcdfFileSequence outputNetcdfFile_;
      OutputLongitudinalProfilesFileSequence outputLongitudinalProfilesFile_;
      OutputCsvModuleRunTableFileSequence outputCsvModuleRunTableFile_;
      PropertiesOptional properties_;
      ::xsd::cxx::tree::one< VersionType > version_;

      //@endcond
    };

    /**
     * @brief Enumeration class corresponding to the %logLevelString
     * schema type.
     */
    class LogLevelString: public ::xml_schema::String
    {
      public:

      /**
       * @brief Underlying enum type.
       */
      enum Value
      {
        /**
         * level designates very severe error events that will presumably lead
         * the application to abort.
         */
        fatal,
        /**
         * level designates error events that	 might still allow the application
         * to continue running
         */
        error,
        /**
         * level designates potentially harmful situations
         */
        warn,
        /**
         * level designates informational messages that highlight the progress of
         * the application at coarse-grained
         */
        info,
        /**
         * level designates informational messages that highlight the progress of
         * the application at coarse-grained
         */
        debug,
        /**
         * Level designates finer-grained informational events than the debug
         */
        trace
      };

      /**
       * @brief Create an instance from the underlying enum value.
       *
       * @param v A enum value.
       */
      LogLevelString (Value v);

      /**
       * @brief Create an instance from a C string.
       *
       * @param v A string value.
       */
      LogLevelString (const char* v);

      /**
       * @brief Create an instance from a string.
       *
       * @param v A string value.
       */
      LogLevelString (const ::std::string& v);

      /**
       * @brief Create an instance from the base value.
       *
       * @param v A base value.
       */
      LogLevelString (const ::xml_schema::String& v);

      /**
       * @brief Create an instance from a DOM element.
       *
       * @param e A DOM element to extract the data from.
       * @param f Flags to create the new instance with.
       * @param c A pointer to the object that will contain the new
       * instance.
       */
      LogLevelString (const ::xercesc::DOMElement& e,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

      /**
       * @brief Create an instance from a DOM attribute.
       *
       * @param a A DOM attribute to extract the data from.
       * @param f Flags to create the new instance with.
       * @param c A pointer to the object that will contain the new
       * instance.
       */
      LogLevelString (const ::xercesc::DOMAttr& a,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

      /**
       * @brief Create an instance from a string fragment.
       *
       * @param s A string fragment to extract the data from.
       * @param e A pointer to DOM element containing the string fragment.
       * @param f Flags to create the new instance with.
       * @param c A pointer to the object that will contain the new
       * instance.
       */
      LogLevelString (const ::std::string& s,
                      const ::xercesc::DOMElement* e,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

      /**
       * @brief Copy constructor.
       *
       * @param x An instance to make a copy of.
       * @param f Flags to create the copy with.
       * @param c A pointer to the object that will contain the copy.
       *
       * For polymorphic object models use the @c _clone function instead.
       */
      LogLevelString (const LogLevelString& x,
                      ::xml_schema::Flags f = 0,
                      ::xml_schema::Container* c = 0);

      /**
       * @brief Copy the instance polymorphically.
       *
       * @param f Flags to create the copy with.
       * @param c A pointer to the object that will contain the copy.
       * @return A pointer to the dynamically allocated copy.
       *
       * This function ensures that the dynamic type of the instance is
       * used for copying and should be used for polymorphic object
       * models instead of the copy constructor.
       */
      virtual LogLevelString*
      _clone (::xml_schema::Flags f = 0,
              ::xml_schema::Container* c = 0) const;

      /**
       * @brief Assign the underlying enum value.
       *
       * @param v A enum value.
       * @return A refernce to the instance.
       */
      LogLevelString&
      operator= (Value v);

      /**
       * @brief Implicit conversion operator to the underlying
       * enum value.
       *
       * @return A enum value.
       */
      virtual
      operator Value () const
      {
        return _xsd_LogLevelString_convert ();
      }

      //@cond

      protected:
      Value
      _xsd_LogLevelString_convert () const;

      public:
      static const char* const _xsd_LogLevelString_literals_[6];
      static const Value _xsd_LogLevelString_indexes_[6];

      //@endcond
    };
  }
}

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

namespace fews
{
  namespace PI
  {
    /**
     * @name Parsing functions for the %Run document root.
     *
     * Since 2008.03. General information about the run executed by the
     * general adapter that is used by the pre and post adapter
     * This file generated on the fly during a pi run file export activity
     * from the General Adapter. This file is read only for the pre and post
     * adapters.
     * A pre or post adapter that supports pi run files only needs this pi
     * run file at the command line argument to find all the pi files it
     * needs to read and write.
     * Other options can be passed to the pre or post adapter by adding extra
     * properties to the generated pi run file during export.
     */
    //@{

    /**
     * @brief Parse a URI or a local file.
     *
     * @param uri A URI or a local file name.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function uses exceptions to report parsing errors.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (const ::std::string& uri,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a URI or a local file with an error handler.
     *
     * @param uri A URI or a local file name.
     * @param eh An error handler.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function reports parsing errors by calling the error handler.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (const ::std::string& uri,
              ::xml_schema::ErrorHandler& eh,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a URI or a local file with a Xerces-C++ DOM error
     * handler.
     *
     * @param uri A URI or a local file name.
     * @param eh A Xerces-C++ DOM error handler.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function reports parsing errors by calling the error handler.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (const ::std::string& uri,
              ::xercesc::DOMErrorHandler& eh,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a standard input stream.
     *
     * @param is A standrad input stream.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function uses exceptions to report parsing errors.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a standard input stream with an error handler.
     *
     * @param is A standrad input stream.
     * @param eh An error handler.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function reports parsing errors by calling the error handler.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              ::xml_schema::ErrorHandler& eh,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a standard input stream with a Xerces-C++ DOM error
     * handler.
     *
     * @param is A standrad input stream.
     * @param eh A Xerces-C++ DOM error handler.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function reports parsing errors by calling the error handler.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              ::xercesc::DOMErrorHandler& eh,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a standard input stream with a resource id.
     *
     * @param is A standrad input stream.
     * @param id A resource id.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * The resource id is used to identify the document being parsed in
     * diagnostics as well as to resolve relative paths.
     *
     * This function uses exceptions to report parsing errors.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              const ::std::string& id,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a standard input stream with a resource id and an
     * error handler.
     *
     * @param is A standrad input stream.
     * @param id A resource id.
     * @param eh An error handler.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * The resource id is used to identify the document being parsed in
     * diagnostics as well as to resolve relative paths.
     *
     * This function reports parsing errors by calling the error handler.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              const ::std::string& id,
              ::xml_schema::ErrorHandler& eh,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a standard input stream with a resource id and a
     * Xerces-C++ DOM error handler.
     *
     * @param is A standrad input stream.
     * @param id A resource id.
     * @param eh A Xerces-C++ DOM error handler.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * The resource id is used to identify the document being parsed in
     * diagnostics as well as to resolve relative paths.
     *
     * This function reports parsing errors by calling the error handler.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::std::istream& is,
              const ::std::string& id,
              ::xercesc::DOMErrorHandler& eh,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a Xerces-C++ input source.
     *
     * @param is A Xerces-C++ input source.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function uses exceptions to report parsing errors.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::xercesc::InputSource& is,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a Xerces-C++ input source with an error handler.
     *
     * @param is A Xerces-C++ input source.
     * @param eh An error handler.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function reports parsing errors by calling the error handler.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::xercesc::InputSource& is,
              ::xml_schema::ErrorHandler& eh,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a Xerces-C++ input source with a Xerces-C++ DOM
     * error handler.
     *
     * @param is A Xerces-C++ input source.
     * @param eh A Xerces-C++ DOM error handler.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function reports parsing errors by calling the error handler.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::xercesc::InputSource& is,
              ::xercesc::DOMErrorHandler& eh,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a Xerces-C++ DOM document.
     *
     * @param d A Xerces-C++ DOM document.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (const ::xercesc::DOMDocument& d,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    /**
     * @brief Parse a Xerces-C++ DOM document.
     *
     * @param d A pointer to the Xerces-C++ DOM document.
     * @param f Parsing flags.
     * @param p Parsing properties. 
     * @return A pointer to the root of the object model.
     *
     * This function is normally used together with the keep_dom and
     * own_dom parsing flags to assign ownership of the DOM document
     * to the object model.
     */
    ::std::auto_ptr< ::fews::PI::RunComplexType >
    parseRun (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
              ::xml_schema::Flags f = 0,
              const ::xml_schema::Properties& p = ::xml_schema::Properties ());

    //@}
  }
}

#include <iosfwd>

#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>
#include <xercesc/framework/XMLFormatter.hpp>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

namespace fews
{
  namespace PI
  {
    /**
     * @name Serialization functions for the %Run document root.
     *
     * Since 2008.03. General information about the run executed by the
     * general adapter that is used by the pre and post adapter
     * This file generated on the fly during a pi run file export activity
     * from the General Adapter. This file is read only for the pre and post
     * adapters.
     * A pre or post adapter that supports pi run files only needs this pi
     * run file at the command line argument to find all the pi files it
     * needs to read and write.
     * Other options can be passed to the pre or post adapter by adding extra
     * properties to the generated pi run file during export.
     */
    //@{

    /**
     * @brief Serialize to a standard output stream.
     *
     * @param os A standrad output stream.
     * @param x An object model to serialize.
     * @param m A namespace information map.
     * @param e A character encoding to produce XML in.
     * @param f Serialization flags.
     *
     * This function uses exceptions to report serialization errors.
     */
    void
    serializeRun (::std::ostream& os,
                  const ::fews::PI::RunComplexType& x, 
                  const ::xml_schema::NamespaceInfomap& m = ::xml_schema::NamespaceInfomap (),
                  const ::std::string& e = "UTF-8",
                  ::xml_schema::Flags f = 0);

    /**
     * @brief Serialize to a standard output stream with an error handler.
     *
     * @param os A standrad output stream.
     * @param x An object model to serialize.
     * @param eh An error handler.
     * @param m A namespace information map.
     * @param e A character encoding to produce XML in.
     * @param f Serialization flags.
     *
     * This function reports serialization errors by calling the error
     * handler.
     */
    void
    serializeRun (::std::ostream& os,
                  const ::fews::PI::RunComplexType& x, 
                  ::xml_schema::ErrorHandler& eh,
                  const ::xml_schema::NamespaceInfomap& m = ::xml_schema::NamespaceInfomap (),
                  const ::std::string& e = "UTF-8",
                  ::xml_schema::Flags f = 0);

    /**
     * @brief Serialize to a standard output stream with a Xerces-C++ DOM
     * error handler.
     *
     * @param os A standrad output stream.
     * @param x An object model to serialize.
     * @param eh A Xerces-C++ DOM error handler.
     * @param m A namespace information map.
     * @param e A character encoding to produce XML in.
     * @param f Serialization flags.
     *
     * This function reports serialization errors by calling the error
     * handler.
     */
    void
    serializeRun (::std::ostream& os,
                  const ::fews::PI::RunComplexType& x, 
                  ::xercesc::DOMErrorHandler& eh,
                  const ::xml_schema::NamespaceInfomap& m = ::xml_schema::NamespaceInfomap (),
                  const ::std::string& e = "UTF-8",
                  ::xml_schema::Flags f = 0);

    /**
     * @brief Serialize to a Xerces-C++ XML format target.
     *
     * @param ft A Xerces-C++ XML format target.
     * @param x An object model to serialize.
     * @param m A namespace information map.
     * @param e A character encoding to produce XML in.
     * @param f Serialization flags.
     *
     * This function uses exceptions to report serialization errors.
     */
    void
    serializeRun (::xercesc::XMLFormatTarget& ft,
                  const ::fews::PI::RunComplexType& x, 
                  const ::xml_schema::NamespaceInfomap& m = ::xml_schema::NamespaceInfomap (),
                  const ::std::string& e = "UTF-8",
                  ::xml_schema::Flags f = 0);

    /**
     * @brief Serialize to a Xerces-C++ XML format target with an error
     * handler.
     *
     * @param ft A Xerces-C++ XML format target.
     * @param x An object model to serialize.
     * @param eh An error handler.
     * @param m A namespace information map.
     * @param e A character encoding to produce XML in.
     * @param f Serialization flags.
     *
     * This function reports serialization errors by calling the error
     * handler.
     */
    void
    serializeRun (::xercesc::XMLFormatTarget& ft,
                  const ::fews::PI::RunComplexType& x, 
                  ::xml_schema::ErrorHandler& eh,
                  const ::xml_schema::NamespaceInfomap& m = ::xml_schema::NamespaceInfomap (),
                  const ::std::string& e = "UTF-8",
                  ::xml_schema::Flags f = 0);

    /**
     * @brief Serialize to a Xerces-C++ XML format target with a
     * Xerces-C++ DOM error handler.
     *
     * @param ft A Xerces-C++ XML format target.
     * @param x An object model to serialize.
     * @param eh A Xerces-C++ DOM error handler.
     * @param m A namespace information map.
     * @param e A character encoding to produce XML in.
     * @param f Serialization flags.
     *
     * This function reports serialization errors by calling the error
     * handler.
     */
    void
    serializeRun (::xercesc::XMLFormatTarget& ft,
                  const ::fews::PI::RunComplexType& x, 
                  ::xercesc::DOMErrorHandler& eh,
                  const ::xml_schema::NamespaceInfomap& m = ::xml_schema::NamespaceInfomap (),
                  const ::std::string& e = "UTF-8",
                  ::xml_schema::Flags f = 0);

    /**
     * @brief Serialize to an existing Xerces-C++ DOM document.
     *
     * @param d A Xerces-C++ DOM document.
     * @param x An object model to serialize.
     * @param f Serialization flags.
     *
     * Note that it is your responsibility to create the DOM document
     * with the correct root element as well as set the necessary
     * namespace mapping attributes.
     */
    void
    serializeRun (::xercesc::DOMDocument& d,
                  const ::fews::PI::RunComplexType& x,
                  ::xml_schema::Flags f = 0);

    /**
     * @brief Serialize to a new Xerces-C++ DOM document.
     *
     * @param x An object model to serialize.
     * @param m A namespace information map.
     * @param f Serialization flags.
     * @return A pointer to the new Xerces-C++ DOM document.
     */
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
    serializeRun (const ::fews::PI::RunComplexType& x, 
                  const ::xml_schema::NamespaceInfomap& m = ::xml_schema::NamespaceInfomap (),
                  ::xml_schema::Flags f = 0);

    //@}

    void
    operator<< (::xercesc::DOMElement&, const RunComplexType&);

    void
    operator<< (::xercesc::DOMElement&, const LogLevelString&);

    void
    operator<< (::xercesc::DOMAttr&, const LogLevelString&);

    void
    operator<< (::xml_schema::ListStream&,
                const LogLevelString&);
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // PI_RUN_HXX
