// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "rtcSharedTypes.hxx"

namespace fews
{
  // TimeStepComplexType
  // 

  const TimeStepComplexType::UnitType& TimeStepComplexType::
  getUnit () const
  {
    return this->unit_.get ();
  }

  TimeStepComplexType::UnitType& TimeStepComplexType::
  getUnit ()
  {
    return this->unit_.get ();
  }

  void TimeStepComplexType::
  setUnit (const UnitType& x)
  {
    this->unit_.set (x);
  }

  void TimeStepComplexType::
  setUnit (::std::auto_ptr< UnitType > x)
  {
    this->unit_.set (x);
  }

  const TimeStepComplexType::DividerType& TimeStepComplexType::
  getDivider () const
  {
    return this->divider_.get ();
  }

  TimeStepComplexType::DividerType& TimeStepComplexType::
  getDivider ()
  {
    return this->divider_.get ();
  }

  void TimeStepComplexType::
  setDivider (const DividerType& x)
  {
    this->divider_.set (x);
  }

  TimeStepComplexType::DividerType TimeStepComplexType::
  getDividerDefaultValue ()
  {
    return DividerType (1ULL);
  }

  const TimeStepComplexType::MultiplierType& TimeStepComplexType::
  getMultiplier () const
  {
    return this->multiplier_.get ();
  }

  TimeStepComplexType::MultiplierType& TimeStepComplexType::
  getMultiplier ()
  {
    return this->multiplier_.get ();
  }

  void TimeStepComplexType::
  setMultiplier (const MultiplierType& x)
  {
    this->multiplier_.set (x);
  }

  TimeStepComplexType::MultiplierType TimeStepComplexType::
  getMultiplierDefaultValue ()
  {
    return MultiplierType (1ULL);
  }


  // TimeStepUnitEnumStringType
  // 

  TimeStepUnitEnumStringType::
  TimeStepUnitEnumStringType (Value v)
  : ::xml_schema::String (_xsd_TimeStepUnitEnumStringType_literals_[v])
  {
  }

  TimeStepUnitEnumStringType::
  TimeStepUnitEnumStringType (const char* v)
  : ::xml_schema::String (v)
  {
  }

  TimeStepUnitEnumStringType::
  TimeStepUnitEnumStringType (const ::std::string& v)
  : ::xml_schema::String (v)
  {
  }

  TimeStepUnitEnumStringType::
  TimeStepUnitEnumStringType (const ::xml_schema::String& v)
  : ::xml_schema::String (v)
  {
  }

  TimeStepUnitEnumStringType::
  TimeStepUnitEnumStringType (const TimeStepUnitEnumStringType& v,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (v, f, c)
  {
  }

  TimeStepUnitEnumStringType& TimeStepUnitEnumStringType::
  operator= (Value v)
  {
    static_cast< ::xml_schema::String& > (*this) = 
    ::xml_schema::String (_xsd_TimeStepUnitEnumStringType_literals_[v]);

    return *this;
  }


  // DateTimeComplexType
  // 

  const DateTimeComplexType::DateType& DateTimeComplexType::
  getDate () const
  {
    return this->date_.get ();
  }

  DateTimeComplexType::DateType& DateTimeComplexType::
  getDate ()
  {
    return this->date_.get ();
  }

  void DateTimeComplexType::
  setDate (const DateType& x)
  {
    this->date_.set (x);
  }

  void DateTimeComplexType::
  setDate (::std::auto_ptr< DateType > x)
  {
    this->date_.set (x);
  }

  const DateTimeComplexType::TimeType& DateTimeComplexType::
  getTime () const
  {
    return this->time_.get ();
  }

  DateTimeComplexType::TimeType& DateTimeComplexType::
  getTime ()
  {
    return this->time_.get ();
  }

  void DateTimeComplexType::
  setTime (const TimeType& x)
  {
    this->time_.set (x);
  }

  void DateTimeComplexType::
  setTime (::std::auto_ptr< TimeType > x)
  {
    this->time_.set (x);
  }


  // DateType
  // 


  // TimeType
  // 


  // VariableTypeEnumStringType
  // 

  VariableTypeEnumStringType::
  VariableTypeEnumStringType (Value v)
  : ::xml_schema::String (_xsd_VariableTypeEnumStringType_literals_[v])
  {
  }

  VariableTypeEnumStringType::
  VariableTypeEnumStringType (const char* v)
  : ::xml_schema::String (v)
  {
  }

  VariableTypeEnumStringType::
  VariableTypeEnumStringType (const ::std::string& v)
  : ::xml_schema::String (v)
  {
  }

  VariableTypeEnumStringType::
  VariableTypeEnumStringType (const ::xml_schema::String& v)
  : ::xml_schema::String (v)
  {
  }

  VariableTypeEnumStringType::
  VariableTypeEnumStringType (const VariableTypeEnumStringType& v,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (v, f, c)
  {
  }

  VariableTypeEnumStringType& VariableTypeEnumStringType::
  operator= (Value v)
  {
    static_cast< ::xml_schema::String& > (*this) = 
    ::xml_schema::String (_xsd_VariableTypeEnumStringType_literals_[v]);

    return *this;
  }


  // EnsembleModeEnumStringType
  // 

  EnsembleModeEnumStringType::
  EnsembleModeEnumStringType (Value v)
  : ::xml_schema::String (_xsd_EnsembleModeEnumStringType_literals_[v])
  {
  }

  EnsembleModeEnumStringType::
  EnsembleModeEnumStringType (const char* v)
  : ::xml_schema::String (v)
  {
  }

  EnsembleModeEnumStringType::
  EnsembleModeEnumStringType (const ::std::string& v)
  : ::xml_schema::String (v)
  {
  }

  EnsembleModeEnumStringType::
  EnsembleModeEnumStringType (const ::xml_schema::String& v)
  : ::xml_schema::String (v)
  {
  }

  EnsembleModeEnumStringType::
  EnsembleModeEnumStringType (const EnsembleModeEnumStringType& v,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (v, f, c)
  {
  }

  EnsembleModeEnumStringType& EnsembleModeEnumStringType::
  operator= (Value v)
  {
    static_cast< ::xml_schema::String& > (*this) = 
    ::xml_schema::String (_xsd_EnsembleModeEnumStringType_literals_[v]);

    return *this;
  }


  // AggregationTypeEnumStringType
  // 

  AggregationTypeEnumStringType::
  AggregationTypeEnumStringType (Value v)
  : ::xml_schema::String (_xsd_AggregationTypeEnumStringType_literals_[v])
  {
  }

  AggregationTypeEnumStringType::
  AggregationTypeEnumStringType (const char* v)
  : ::xml_schema::String (v)
  {
  }

  AggregationTypeEnumStringType::
  AggregationTypeEnumStringType (const ::std::string& v)
  : ::xml_schema::String (v)
  {
  }

  AggregationTypeEnumStringType::
  AggregationTypeEnumStringType (const ::xml_schema::String& v)
  : ::xml_schema::String (v)
  {
  }

  AggregationTypeEnumStringType::
  AggregationTypeEnumStringType (const AggregationTypeEnumStringType& v,
                                 ::xml_schema::Flags f,
                                 ::xml_schema::Container* c)
  : ::xml_schema::String (v, f, c)
  {
  }

  AggregationTypeEnumStringType& AggregationTypeEnumStringType::
  operator= (Value v)
  {
    static_cast< ::xml_schema::String& > (*this) = 
    ::xml_schema::String (_xsd_AggregationTypeEnumStringType_literals_[v]);

    return *this;
  }


  // TimeZoneSimpleType
  // 


  // TimeSeriesType
  // 

  TimeSeriesType::
  TimeSeriesType (Value v)
  : ::xml_schema::String (_xsd_TimeSeriesType_literals_[v])
  {
  }

  TimeSeriesType::
  TimeSeriesType (const char* v)
  : ::xml_schema::String (v)
  {
  }

  TimeSeriesType::
  TimeSeriesType (const ::std::string& v)
  : ::xml_schema::String (v)
  {
  }

  TimeSeriesType::
  TimeSeriesType (const ::xml_schema::String& v)
  : ::xml_schema::String (v)
  {
  }

  TimeSeriesType::
  TimeSeriesType (const TimeSeriesType& v,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
  : ::xml_schema::String (v, f, c)
  {
  }

  TimeSeriesType& TimeSeriesType::
  operator= (Value v)
  {
    static_cast< ::xml_schema::String& > (*this) = 
    ::xml_schema::String (_xsd_TimeSeriesType_literals_[v]);

    return *this;
  }


  // ExternalParameterSimpleType
  //

  ExternalParameterSimpleType::
  ExternalParameterSimpleType (const char* s)
  : ::xml_schema::String (s)
  {
  }

  ExternalParameterSimpleType::
  ExternalParameterSimpleType (const ::std::string& s)
  : ::xml_schema::String (s)
  {
  }

  ExternalParameterSimpleType::
  ExternalParameterSimpleType (const ExternalParameterSimpleType& o,
                               ::xml_schema::Flags f,
                               ::xml_schema::Container* c)
  : ::xml_schema::String (o, f, c)
  {
  }

  // ExternalBooleanSimpleType
  //

  ExternalBooleanSimpleType::
  ExternalBooleanSimpleType (const char* s)
  : ::xml_schema::String (s)
  {
  }

  ExternalBooleanSimpleType::
  ExternalBooleanSimpleType (const ::std::string& s)
  : ::xml_schema::String (s)
  {
  }

  ExternalBooleanSimpleType::
  ExternalBooleanSimpleType (const ExternalBooleanSimpleType& o,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
  : ::xml_schema::String (o, f, c)
  {
  }

  // ExternalIntegerSimpleType
  //

  ExternalIntegerSimpleType::
  ExternalIntegerSimpleType (const char* s)
  : ::xml_schema::String (s)
  {
  }

  ExternalIntegerSimpleType::
  ExternalIntegerSimpleType (const ::std::string& s)
  : ::xml_schema::String (s)
  {
  }

  ExternalIntegerSimpleType::
  ExternalIntegerSimpleType (const ExternalIntegerSimpleType& o,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
  : ::xml_schema::String (o, f, c)
  {
  }

  // TimeSeriesSimpleType
  // 


  // ExternalParameterSimpleType_member
  // 


  // ExternalBooleanSimpleType_member
  // 


  // ExternalIntegerSimpleType_member
  // 
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace fews
{
  // TimeStepComplexType
  //

  TimeStepComplexType::
  TimeStepComplexType (const UnitType& unit)
  : ::xml_schema::Type (),
    unit_ (unit, ::xml_schema::Flags (), this),
    divider_ (getDividerDefaultValue (), ::xml_schema::Flags (), this),
    multiplier_ (getMultiplierDefaultValue (), ::xml_schema::Flags (), this)
  {
  }

  TimeStepComplexType::
  TimeStepComplexType (const TimeStepComplexType& x,
                       ::xml_schema::Flags f,
                       ::xml_schema::Container* c)
  : ::xml_schema::Type (x, f, c),
    unit_ (x.unit_, f, this),
    divider_ (x.divider_, f, this),
    multiplier_ (x.multiplier_, f, this)
  {
  }

  TimeStepComplexType::
  TimeStepComplexType (const ::xercesc::DOMElement& e,
                       ::xml_schema::Flags f,
                       ::xml_schema::Container* c)
  : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
    unit_ (f, this),
    divider_ (f, this),
    multiplier_ (f, this)
  {
    if ((f & ::xml_schema::Flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, true);
      this->parse (p, f);
    }
  }

  void TimeStepComplexType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::Flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "unit" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< UnitType > r (
          UnitTraits::create (i, f, this));

        this->unit_.set (r);
        continue;
      }

      if (n.name () == "divider" && n.namespace_ ().empty ())
      {
        this->divider_.set (DividerTraits::create (i, f, this));
        continue;
      }

      if (n.name () == "multiplier" && n.namespace_ ().empty ())
      {
        this->multiplier_.set (MultiplierTraits::create (i, f, this));
        continue;
      }
    }

    if (!unit_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "unit",
        "");
    }

    if (!divider_.present ())
    {
      this->divider_.set (getDividerDefaultValue ());
    }

    if (!multiplier_.present ())
    {
      this->multiplier_.set (getMultiplierDefaultValue ());
    }
  }

  TimeStepComplexType* TimeStepComplexType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class TimeStepComplexType (*this, f, c);
  }

  TimeStepComplexType::
  ~TimeStepComplexType ()
  {
  }

  // TimeStepUnitEnumStringType
  //

  TimeStepUnitEnumStringType::
  TimeStepUnitEnumStringType (const ::xercesc::DOMElement& e,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
    _xsd_TimeStepUnitEnumStringType_convert ();
  }

  TimeStepUnitEnumStringType::
  TimeStepUnitEnumStringType (const ::xercesc::DOMAttr& a,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
    _xsd_TimeStepUnitEnumStringType_convert ();
  }

  TimeStepUnitEnumStringType::
  TimeStepUnitEnumStringType (const ::std::string& s,
                              const ::xercesc::DOMElement* e,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
    _xsd_TimeStepUnitEnumStringType_convert ();
  }

  TimeStepUnitEnumStringType* TimeStepUnitEnumStringType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class TimeStepUnitEnumStringType (*this, f, c);
  }

  TimeStepUnitEnumStringType::Value TimeStepUnitEnumStringType::
  _xsd_TimeStepUnitEnumStringType_convert () const
  {
    ::xsd::cxx::tree::enum_comparator< char > c (_xsd_TimeStepUnitEnumStringType_literals_);
    const Value* i (::std::lower_bound (
                      _xsd_TimeStepUnitEnumStringType_indexes_,
                      _xsd_TimeStepUnitEnumStringType_indexes_ + 5,
                      *this,
                      c));

    if (i == _xsd_TimeStepUnitEnumStringType_indexes_ + 5 || _xsd_TimeStepUnitEnumStringType_literals_[*i] != *this)
    {
      throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
    }

    return *i;
  }

  const char* const TimeStepUnitEnumStringType::
  _xsd_TimeStepUnitEnumStringType_literals_[5] =
  {
    "second",
    "minute",
    "hour",
    "day",
    "week"
  };

  const TimeStepUnitEnumStringType::Value TimeStepUnitEnumStringType::
  _xsd_TimeStepUnitEnumStringType_indexes_[5] =
  {
    ::fews::TimeStepUnitEnumStringType::day,
    ::fews::TimeStepUnitEnumStringType::hour,
    ::fews::TimeStepUnitEnumStringType::minute,
    ::fews::TimeStepUnitEnumStringType::second,
    ::fews::TimeStepUnitEnumStringType::week
  };

  // DateTimeComplexType
  //

  DateTimeComplexType::
  DateTimeComplexType (const DateType& date,
                       const TimeType& time)
  : ::xml_schema::Type (),
    date_ (date, ::xml_schema::Flags (), this),
    time_ (time, ::xml_schema::Flags (), this)
  {
  }

  DateTimeComplexType::
  DateTimeComplexType (const DateTimeComplexType& x,
                       ::xml_schema::Flags f,
                       ::xml_schema::Container* c)
  : ::xml_schema::Type (x, f, c),
    date_ (x.date_, f, this),
    time_ (x.time_, f, this)
  {
  }

  DateTimeComplexType::
  DateTimeComplexType (const ::xercesc::DOMElement& e,
                       ::xml_schema::Flags f,
                       ::xml_schema::Container* c)
  : ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
    date_ (f, this),
    time_ (f, this)
  {
    if ((f & ::xml_schema::Flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, false, true);
      this->parse (p, f);
    }
  }

  void DateTimeComplexType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::Flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "date" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< DateType > r (
          DateTraits::create (i, f, this));

        this->date_.set (r);
        continue;
      }

      if (n.name () == "time" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< TimeType > r (
          TimeTraits::create (i, f, this));

        this->time_.set (r);
        continue;
      }
    }

    if (!date_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "date",
        "");
    }

    if (!time_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< char > (
        "time",
        "");
    }
  }

  DateTimeComplexType* DateTimeComplexType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class DateTimeComplexType (*this, f, c);
  }

  DateTimeComplexType::
  ~DateTimeComplexType ()
  {
  }

  // DateType
  //

  DateType::
  DateType (const ::xml_schema::Date& _xsd_Date_base)
  : ::xml_schema::Date (_xsd_Date_base)
  {
  }

  DateType::
  DateType (const DateType& x,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
  : ::xml_schema::Date (x, f, c)
  {
  }

  DateType::
  DateType (const ::xercesc::DOMElement& e,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
  : ::xml_schema::Date (e, f, c)
  {
  }

  DateType::
  DateType (const ::xercesc::DOMAttr& a,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
  : ::xml_schema::Date (a, f, c)
  {
  }

  DateType::
  DateType (const ::std::string& s,
            const ::xercesc::DOMElement* e,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
  : ::xml_schema::Date (s, e, f, c)
  {
  }

  DateType* DateType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class DateType (*this, f, c);
  }

  DateType::
  ~DateType ()
  {
  }

  // TimeType
  //

  TimeType::
  TimeType (const ::xml_schema::Time& _xsd_Time_base)
  : ::xml_schema::Time (_xsd_Time_base)
  {
  }

  TimeType::
  TimeType (const TimeType& x,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
  : ::xml_schema::Time (x, f, c)
  {
  }

  TimeType::
  TimeType (const ::xercesc::DOMElement& e,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
  : ::xml_schema::Time (e, f, c)
  {
  }

  TimeType::
  TimeType (const ::xercesc::DOMAttr& a,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
  : ::xml_schema::Time (a, f, c)
  {
  }

  TimeType::
  TimeType (const ::std::string& s,
            const ::xercesc::DOMElement* e,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
  : ::xml_schema::Time (s, e, f, c)
  {
  }

  TimeType* TimeType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class TimeType (*this, f, c);
  }

  TimeType::
  ~TimeType ()
  {
  }

  // VariableTypeEnumStringType
  //

  VariableTypeEnumStringType::
  VariableTypeEnumStringType (const ::xercesc::DOMElement& e,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
    _xsd_VariableTypeEnumStringType_convert ();
  }

  VariableTypeEnumStringType::
  VariableTypeEnumStringType (const ::xercesc::DOMAttr& a,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
    _xsd_VariableTypeEnumStringType_convert ();
  }

  VariableTypeEnumStringType::
  VariableTypeEnumStringType (const ::std::string& s,
                              const ::xercesc::DOMElement* e,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
    _xsd_VariableTypeEnumStringType_convert ();
  }

  VariableTypeEnumStringType* VariableTypeEnumStringType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class VariableTypeEnumStringType (*this, f, c);
  }

  VariableTypeEnumStringType::Value VariableTypeEnumStringType::
  _xsd_VariableTypeEnumStringType_convert () const
  {
    ::xsd::cxx::tree::enum_comparator< char > c (_xsd_VariableTypeEnumStringType_literals_);
    const Value* i (::std::lower_bound (
                      _xsd_VariableTypeEnumStringType_indexes_,
                      _xsd_VariableTypeEnumStringType_indexes_ + 3,
                      *this,
                      c));

    if (i == _xsd_VariableTypeEnumStringType_indexes_ + 3 || _xsd_VariableTypeEnumStringType_literals_[*i] != *this)
    {
      throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
    }

    return *i;
  }

  const char* const VariableTypeEnumStringType::
  _xsd_VariableTypeEnumStringType_literals_[3] =
  {
    "CONTINUOUS",
    "INTEGER",
    "TIMEINSTANCE"
  };

  const VariableTypeEnumStringType::Value VariableTypeEnumStringType::
  _xsd_VariableTypeEnumStringType_indexes_[3] =
  {
    ::fews::VariableTypeEnumStringType::CONTINUOUS,
    ::fews::VariableTypeEnumStringType::INTEGER,
    ::fews::VariableTypeEnumStringType::TIMEINSTANCE
  };

  // EnsembleModeEnumStringType
  //

  EnsembleModeEnumStringType::
  EnsembleModeEnumStringType (const ::xercesc::DOMElement& e,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
    _xsd_EnsembleModeEnumStringType_convert ();
  }

  EnsembleModeEnumStringType::
  EnsembleModeEnumStringType (const ::xercesc::DOMAttr& a,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
    _xsd_EnsembleModeEnumStringType_convert ();
  }

  EnsembleModeEnumStringType::
  EnsembleModeEnumStringType (const ::std::string& s,
                              const ::xercesc::DOMElement* e,
                              ::xml_schema::Flags f,
                              ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
    _xsd_EnsembleModeEnumStringType_convert ();
  }

  EnsembleModeEnumStringType* EnsembleModeEnumStringType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class EnsembleModeEnumStringType (*this, f, c);
  }

  EnsembleModeEnumStringType::Value EnsembleModeEnumStringType::
  _xsd_EnsembleModeEnumStringType_convert () const
  {
    ::xsd::cxx::tree::enum_comparator< char > c (_xsd_EnsembleModeEnumStringType_literals_);
    const Value* i (::std::lower_bound (
                      _xsd_EnsembleModeEnumStringType_indexes_,
                      _xsd_EnsembleModeEnumStringType_indexes_ + 3,
                      *this,
                      c));

    if (i == _xsd_EnsembleModeEnumStringType_indexes_ + 3 || _xsd_EnsembleModeEnumStringType_literals_[*i] != *this)
    {
      throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
    }

    return *i;
  }

  const char* const EnsembleModeEnumStringType::
  _xsd_EnsembleModeEnumStringType_literals_[3] =
  {
    "JOINT",
    "TREE",
    "INDEPENDENT"
  };

  const EnsembleModeEnumStringType::Value EnsembleModeEnumStringType::
  _xsd_EnsembleModeEnumStringType_indexes_[3] =
  {
    ::fews::EnsembleModeEnumStringType::INDEPENDENT,
    ::fews::EnsembleModeEnumStringType::JOINT,
    ::fews::EnsembleModeEnumStringType::TREE
  };

  // AggregationTypeEnumStringType
  //

  AggregationTypeEnumStringType::
  AggregationTypeEnumStringType (const ::xercesc::DOMElement& e,
                                 ::xml_schema::Flags f,
                                 ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
    _xsd_AggregationTypeEnumStringType_convert ();
  }

  AggregationTypeEnumStringType::
  AggregationTypeEnumStringType (const ::xercesc::DOMAttr& a,
                                 ::xml_schema::Flags f,
                                 ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
    _xsd_AggregationTypeEnumStringType_convert ();
  }

  AggregationTypeEnumStringType::
  AggregationTypeEnumStringType (const ::std::string& s,
                                 const ::xercesc::DOMElement* e,
                                 ::xml_schema::Flags f,
                                 ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
    _xsd_AggregationTypeEnumStringType_convert ();
  }

  AggregationTypeEnumStringType* AggregationTypeEnumStringType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class AggregationTypeEnumStringType (*this, f, c);
  }

  AggregationTypeEnumStringType::Value AggregationTypeEnumStringType::
  _xsd_AggregationTypeEnumStringType_convert () const
  {
    ::xsd::cxx::tree::enum_comparator< char > c (_xsd_AggregationTypeEnumStringType_literals_);
    const Value* i (::std::lower_bound (
                      _xsd_AggregationTypeEnumStringType_indexes_,
                      _xsd_AggregationTypeEnumStringType_indexes_ + 2,
                      *this,
                      c));

    if (i == _xsd_AggregationTypeEnumStringType_indexes_ + 2 || _xsd_AggregationTypeEnumStringType_literals_[*i] != *this)
    {
      throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
    }

    return *i;
  }

  const char* const AggregationTypeEnumStringType::
  _xsd_AggregationTypeEnumStringType_literals_[2] =
  {
    "BLOCK",
    "LINEAR"
  };

  const AggregationTypeEnumStringType::Value AggregationTypeEnumStringType::
  _xsd_AggregationTypeEnumStringType_indexes_[2] =
  {
    ::fews::AggregationTypeEnumStringType::BLOCK,
    ::fews::AggregationTypeEnumStringType::LINEAR
  };

  // TimeZoneSimpleType
  //

  TimeZoneSimpleType::
  TimeZoneSimpleType (const ::xml_schema::Double& _xsd_Double_base)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::Double, char, ::xml_schema::SimpleType, ::xsd::cxx::tree::schema_type::double_ > (_xsd_Double_base)
  {
  }

  TimeZoneSimpleType::
  TimeZoneSimpleType (const TimeZoneSimpleType& x,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::Double, char, ::xml_schema::SimpleType, ::xsd::cxx::tree::schema_type::double_ > (x, f, c)
  {
  }

  TimeZoneSimpleType::
  TimeZoneSimpleType (const ::xercesc::DOMElement& e,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::Double, char, ::xml_schema::SimpleType, ::xsd::cxx::tree::schema_type::double_ > (e, f, c)
  {
  }

  TimeZoneSimpleType::
  TimeZoneSimpleType (const ::xercesc::DOMAttr& a,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::Double, char, ::xml_schema::SimpleType, ::xsd::cxx::tree::schema_type::double_ > (a, f, c)
  {
  }

  TimeZoneSimpleType::
  TimeZoneSimpleType (const ::std::string& s,
                      const ::xercesc::DOMElement* e,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
  : ::xsd::cxx::tree::fundamental_base< ::xml_schema::Double, char, ::xml_schema::SimpleType, ::xsd::cxx::tree::schema_type::double_ > (s, e, f, c)
  {
  }

  TimeZoneSimpleType* TimeZoneSimpleType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class TimeZoneSimpleType (*this, f, c);
  }

  TimeZoneSimpleType::
  ~TimeZoneSimpleType ()
  {
  }

  // TimeSeriesType
  //

  TimeSeriesType::
  TimeSeriesType (const ::xercesc::DOMElement& e,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
    _xsd_TimeSeriesType_convert ();
  }

  TimeSeriesType::
  TimeSeriesType (const ::xercesc::DOMAttr& a,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
    _xsd_TimeSeriesType_convert ();
  }

  TimeSeriesType::
  TimeSeriesType (const ::std::string& s,
                  const ::xercesc::DOMElement* e,
                  ::xml_schema::Flags f,
                  ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
    _xsd_TimeSeriesType_convert ();
  }

  TimeSeriesType* TimeSeriesType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class TimeSeriesType (*this, f, c);
  }

  TimeSeriesType::Value TimeSeriesType::
  _xsd_TimeSeriesType_convert () const
  {
    ::xsd::cxx::tree::enum_comparator< char > c (_xsd_TimeSeriesType_literals_);
    const Value* i (::std::lower_bound (
                      _xsd_TimeSeriesType_indexes_,
                      _xsd_TimeSeriesType_indexes_ + 2,
                      *this,
                      c));

    if (i == _xsd_TimeSeriesType_indexes_ + 2 || _xsd_TimeSeriesType_literals_[*i] != *this)
    {
      throw ::xsd::cxx::tree::unexpected_enumerator < char > (*this);
    }

    return *i;
  }

  const char* const TimeSeriesType::
  _xsd_TimeSeriesType_literals_[2] =
  {
    "accumulative",
    "instantaneous"
  };

  const TimeSeriesType::Value TimeSeriesType::
  _xsd_TimeSeriesType_indexes_[2] =
  {
    ::fews::TimeSeriesType::accumulative,
    ::fews::TimeSeriesType::instantaneous
  };

  // ExternalParameterSimpleType
  //

  ExternalParameterSimpleType::
  ExternalParameterSimpleType (const ::xercesc::DOMElement& e,
                               ::xml_schema::Flags f,
                               ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
  }

  ExternalParameterSimpleType::
  ExternalParameterSimpleType (const ::xercesc::DOMAttr& a,
                               ::xml_schema::Flags f,
                               ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
  }

  ExternalParameterSimpleType::
  ExternalParameterSimpleType (const ::std::string& s,
                               const ::xercesc::DOMElement* e,
                               ::xml_schema::Flags f,
                               ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
  }

  ExternalParameterSimpleType* ExternalParameterSimpleType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class ExternalParameterSimpleType (*this, f, c);
  }

  // ExternalBooleanSimpleType
  //

  ExternalBooleanSimpleType::
  ExternalBooleanSimpleType (const ::xercesc::DOMElement& e,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
  }

  ExternalBooleanSimpleType::
  ExternalBooleanSimpleType (const ::xercesc::DOMAttr& a,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
  }

  ExternalBooleanSimpleType::
  ExternalBooleanSimpleType (const ::std::string& s,
                             const ::xercesc::DOMElement* e,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
  }

  ExternalBooleanSimpleType* ExternalBooleanSimpleType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class ExternalBooleanSimpleType (*this, f, c);
  }

  // ExternalIntegerSimpleType
  //

  ExternalIntegerSimpleType::
  ExternalIntegerSimpleType (const ::xercesc::DOMElement& e,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
  }

  ExternalIntegerSimpleType::
  ExternalIntegerSimpleType (const ::xercesc::DOMAttr& a,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
  }

  ExternalIntegerSimpleType::
  ExternalIntegerSimpleType (const ::std::string& s,
                             const ::xercesc::DOMElement* e,
                             ::xml_schema::Flags f,
                             ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
  }

  ExternalIntegerSimpleType* ExternalIntegerSimpleType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class ExternalIntegerSimpleType (*this, f, c);
  }

  // TimeSeriesSimpleType
  //

  TimeSeriesSimpleType::
  TimeSeriesSimpleType ()
  : ::xml_schema::String ()
  {
  }

  TimeSeriesSimpleType::
  TimeSeriesSimpleType (const char* _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  TimeSeriesSimpleType::
  TimeSeriesSimpleType (const ::std::string& _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  TimeSeriesSimpleType::
  TimeSeriesSimpleType (const ::xml_schema::String& _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  TimeSeriesSimpleType::
  TimeSeriesSimpleType (const TimeSeriesSimpleType& x,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
  : ::xml_schema::String (x, f, c)
  {
  }

  TimeSeriesSimpleType::
  TimeSeriesSimpleType (const ::xercesc::DOMElement& e,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
  }

  TimeSeriesSimpleType::
  TimeSeriesSimpleType (const ::xercesc::DOMAttr& a,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
  }

  TimeSeriesSimpleType::
  TimeSeriesSimpleType (const ::std::string& s,
                        const ::xercesc::DOMElement* e,
                        ::xml_schema::Flags f,
                        ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
  }

  TimeSeriesSimpleType* TimeSeriesSimpleType::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class TimeSeriesSimpleType (*this, f, c);
  }

  TimeSeriesSimpleType::
  ~TimeSeriesSimpleType ()
  {
  }

  // ExternalParameterSimpleType_member
  //

  ExternalParameterSimpleType_member::
  ExternalParameterSimpleType_member ()
  : ::xml_schema::String ()
  {
  }

  ExternalParameterSimpleType_member::
  ExternalParameterSimpleType_member (const char* _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalParameterSimpleType_member::
  ExternalParameterSimpleType_member (const ::std::string& _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalParameterSimpleType_member::
  ExternalParameterSimpleType_member (const ::xml_schema::String& _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalParameterSimpleType_member::
  ExternalParameterSimpleType_member (const ExternalParameterSimpleType_member& x,
                                      ::xml_schema::Flags f,
                                      ::xml_schema::Container* c)
  : ::xml_schema::String (x, f, c)
  {
  }

  ExternalParameterSimpleType_member::
  ExternalParameterSimpleType_member (const ::xercesc::DOMElement& e,
                                      ::xml_schema::Flags f,
                                      ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
  }

  ExternalParameterSimpleType_member::
  ExternalParameterSimpleType_member (const ::xercesc::DOMAttr& a,
                                      ::xml_schema::Flags f,
                                      ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
  }

  ExternalParameterSimpleType_member::
  ExternalParameterSimpleType_member (const ::std::string& s,
                                      const ::xercesc::DOMElement* e,
                                      ::xml_schema::Flags f,
                                      ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
  }

  ExternalParameterSimpleType_member* ExternalParameterSimpleType_member::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class ExternalParameterSimpleType_member (*this, f, c);
  }

  ExternalParameterSimpleType_member::
  ~ExternalParameterSimpleType_member ()
  {
  }

  // ExternalBooleanSimpleType_member
  //

  ExternalBooleanSimpleType_member::
  ExternalBooleanSimpleType_member ()
  : ::xml_schema::String ()
  {
  }

  ExternalBooleanSimpleType_member::
  ExternalBooleanSimpleType_member (const char* _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalBooleanSimpleType_member::
  ExternalBooleanSimpleType_member (const ::std::string& _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalBooleanSimpleType_member::
  ExternalBooleanSimpleType_member (const ::xml_schema::String& _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalBooleanSimpleType_member::
  ExternalBooleanSimpleType_member (const ExternalBooleanSimpleType_member& x,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
  : ::xml_schema::String (x, f, c)
  {
  }

  ExternalBooleanSimpleType_member::
  ExternalBooleanSimpleType_member (const ::xercesc::DOMElement& e,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
  }

  ExternalBooleanSimpleType_member::
  ExternalBooleanSimpleType_member (const ::xercesc::DOMAttr& a,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
  }

  ExternalBooleanSimpleType_member::
  ExternalBooleanSimpleType_member (const ::std::string& s,
                                    const ::xercesc::DOMElement* e,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
  }

  ExternalBooleanSimpleType_member* ExternalBooleanSimpleType_member::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class ExternalBooleanSimpleType_member (*this, f, c);
  }

  ExternalBooleanSimpleType_member::
  ~ExternalBooleanSimpleType_member ()
  {
  }

  // ExternalIntegerSimpleType_member
  //

  ExternalIntegerSimpleType_member::
  ExternalIntegerSimpleType_member ()
  : ::xml_schema::String ()
  {
  }

  ExternalIntegerSimpleType_member::
  ExternalIntegerSimpleType_member (const char* _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalIntegerSimpleType_member::
  ExternalIntegerSimpleType_member (const ::std::string& _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalIntegerSimpleType_member::
  ExternalIntegerSimpleType_member (const ::xml_schema::String& _xsd_String_base)
  : ::xml_schema::String (_xsd_String_base)
  {
  }

  ExternalIntegerSimpleType_member::
  ExternalIntegerSimpleType_member (const ExternalIntegerSimpleType_member& x,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
  : ::xml_schema::String (x, f, c)
  {
  }

  ExternalIntegerSimpleType_member::
  ExternalIntegerSimpleType_member (const ::xercesc::DOMElement& e,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
  : ::xml_schema::String (e, f, c)
  {
  }

  ExternalIntegerSimpleType_member::
  ExternalIntegerSimpleType_member (const ::xercesc::DOMAttr& a,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
  : ::xml_schema::String (a, f, c)
  {
  }

  ExternalIntegerSimpleType_member::
  ExternalIntegerSimpleType_member (const ::std::string& s,
                                    const ::xercesc::DOMElement* e,
                                    ::xml_schema::Flags f,
                                    ::xml_schema::Container* c)
  : ::xml_schema::String (s, e, f, c)
  {
  }

  ExternalIntegerSimpleType_member* ExternalIntegerSimpleType_member::
  _clone (::xml_schema::Flags f,
          ::xml_schema::Container* c) const
  {
    return new class ExternalIntegerSimpleType_member (*this, f, c);
  }

  ExternalIntegerSimpleType_member::
  ~ExternalIntegerSimpleType_member ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace fews
{
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace fews
{
  void
  operator<< (::xercesc::DOMElement& e, const TimeStepComplexType& i)
  {
    e << static_cast< const ::xml_schema::Type& > (i);

    // unit
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "unit",
          e));

      a << i.getUnit ();
    }

    // divider
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "divider",
          e));

      a << i.getDivider ();
    }

    // multiplier
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "multiplier",
          e));

      a << i.getMultiplier ();
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const TimeStepUnitEnumStringType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const TimeStepUnitEnumStringType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const TimeStepUnitEnumStringType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const DateTimeComplexType& i)
  {
    e << static_cast< const ::xml_schema::Type& > (i);

    // date
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "date",
          e));

      a << i.getDate ();
    }

    // time
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "time",
          e));

      a << i.getTime ();
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const DateType& i)
  {
    e << static_cast< const ::xml_schema::Date& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const DateType& i)
  {
    a << static_cast< const ::xml_schema::Date& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const DateType& i)
  {
    l << static_cast< const ::xml_schema::Date& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const TimeType& i)
  {
    e << static_cast< const ::xml_schema::Time& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const TimeType& i)
  {
    a << static_cast< const ::xml_schema::Time& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const TimeType& i)
  {
    l << static_cast< const ::xml_schema::Time& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const VariableTypeEnumStringType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const VariableTypeEnumStringType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const VariableTypeEnumStringType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const EnsembleModeEnumStringType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const EnsembleModeEnumStringType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const EnsembleModeEnumStringType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const AggregationTypeEnumStringType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const AggregationTypeEnumStringType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const AggregationTypeEnumStringType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const TimeZoneSimpleType& i)
  {
    e << static_cast< const ::xsd::cxx::tree::fundamental_base< ::xml_schema::Double, char, ::xml_schema::SimpleType, ::xsd::cxx::tree::schema_type::double_ >& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const TimeZoneSimpleType& i)
  {
    a << static_cast< const ::xsd::cxx::tree::fundamental_base< ::xml_schema::Double, char, ::xml_schema::SimpleType, ::xsd::cxx::tree::schema_type::double_ >& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const TimeZoneSimpleType& i)
  {
    l << static_cast< const ::xsd::cxx::tree::fundamental_base< ::xml_schema::Double, char, ::xml_schema::SimpleType, ::xsd::cxx::tree::schema_type::double_ >& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const TimeSeriesType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const TimeSeriesType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const TimeSeriesType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const ExternalParameterSimpleType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const ExternalParameterSimpleType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const ExternalParameterSimpleType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const ExternalBooleanSimpleType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const ExternalBooleanSimpleType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const ExternalBooleanSimpleType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const ExternalIntegerSimpleType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const ExternalIntegerSimpleType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const ExternalIntegerSimpleType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const TimeSeriesSimpleType& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const TimeSeriesSimpleType& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const TimeSeriesSimpleType& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const ExternalParameterSimpleType_member& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const ExternalParameterSimpleType_member& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const ExternalParameterSimpleType_member& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const ExternalBooleanSimpleType_member& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const ExternalBooleanSimpleType_member& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const ExternalBooleanSimpleType_member& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMElement& e, const ExternalIntegerSimpleType_member& i)
  {
    e << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xercesc::DOMAttr& a, const ExternalIntegerSimpleType_member& i)
  {
    a << static_cast< const ::xml_schema::String& > (i);
  }

  void
  operator<< (::xml_schema::ListStream& l,
              const ExternalIntegerSimpleType_member& i)
  {
    l << static_cast< const ::xml_schema::String& > (i);
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

