subroutine CSTABL(ngrid  ,maxlev ,nlev   ,hlev   ,wft    ,aft    ,&
&wtt    ,att    ,of     ,lsalt  ,izwft  ,nbran  ,&
&branch ,typcr  ,sectc  ,sectv  ,prslot ,psltvr ,&
&bfrict ,bfricp ,engpar ,grsize ,&
&maxtab ,ntabm  ,ntab   ,table  ,ws     ,lsedt  ,&
&juer   ,ker    )

!=======================================================================
!            Rijkswaterstaat/RIZA and DELFT HYDRAULICS
!                One Dimensional Modelling System
!                           S O B E K
!-----------------------------------------------------------------------
! Subsystem:          Cross Sectional Table Module
!
! Programmer:         J.Brouwer
!
! Module:             CSTABL (Cross Sectional TABLes)
!
! Module description: In subroutine CSTABL the following tables will be
!                     generated:
!
!                     - flow areas;
!                     - total areas;
!                     - wetted perimeter
!                     - integrated zWf(z)dz
!
!                     In addition tables related to vertical division of
!                     cross sections will be generated for:
!
!                     - flow area Af(h0) for main section
!                     - flow area Af(h1) for sub section 1
!                     - wetted perimeter O0 for main section
!                     - wetted perimeter O1 for sub section 1
!
!                     The last step of this module concerns the creation
!                     of preissmann slots (funnel) for normal branches. A
!                     slot will be created if the user selected this option.
!
!                     In subroutine CSTABL tables will be computed for
!                     the flow and total area as well as the wetted
!                     perimeters. Input for this subroutine are the
!                     tables with flow and total widths. These tables
!                     are supplied by the user or are read from a
!                     restart file. CSTABL must be called at the start
!                     of a simulation and each time the morphology mod-
!                     ule adapted the bed levels.
!
!                     The calculation will only be performed for
!                     branches with the cross section type 'TABLE'. For
!                     the other possibilities 'CIRCLE' and 'SEDREDGE'
!                     special routines are used which calculate the
!                     different parameters numerically.
!
!                     The area tables will be generated by means of
!                     numerical integration (CSINTG).
!
!                     The table of wetted perimeters is computed in
!                     subroutine CSPERI from the table of flow widths !
!                     The table with integrated Wf(z) is calculated in
!                     subroutine CSZWFZ.
!
!                     Subroutine CSSECT computes some parameters needed
!                     for the Chezy computation in main sections and sub
!                     sections. In this subroutine the time-independent
!                     parameters:
!
!                     Af(h0) = flow area in the main section for h=h0,
!                     and
!                     Af(h1) = flow area in sub section 1 for h=h1, will
!                     be computed.
!
!                     In addition in subroutine CSSECT the time indepen-
!                     dent wetted perimeters O0 and O1 will be computed,
!                     for main section (h=h0) resp. sub section 1
!                     (h=h1).
!
!-----------------------------------------------------------------------
! Parameters:
! NR NAME              IO DESCRIPTION
!  6 aft               P  -
!  8 att               P  -
! 20 bfricp            P  -
! 19 bfrict            P  -
! 13 branch            P  -
! 21 engpar            P  -
! 22 grsize            P  -
!  4 hlev              P  -
! 11 izwft             P  -
! 27 juer              P  -
! 28 ker               P  -
! 10 lsalt             I  Logical indicator for salt computation
!                         = .true.  : with salt computation
!                         = .false. : no salt computation
!  2 maxlev            I  Maximum+1 over nlev(1:ngrid); needed for
!                         declarations
! 23 maxtab            I  Maximum number of defined tables.
! 12 nbran             I  Number of branches.
!  1 ngrid             I  Number of grid points in network.
!  3 nlev              P  -
! 25 ntab              P  -
! 24 ntabm             I  Maximum size of table (Used for dimensioning
!                         table).
!  9 of                P  -
! 17 prslot(3,nbran)   I  Contains information concerning Preissmann
!                         slot (assuring positive water depths).
!                         (1,i) = Create slot indicator
!                                 csldis (0) : No slot in this branch.
!                                 cslena (1) : Create slot in branch.
!                         (2,i) = Reference area for slot generation.
!                         (3,i) = Depth of slot below lowest bottom of
!                                 branch.
! 18 psltvr            P  -
! 15 sectc             P  -
! 16 sectv             P  -
! 26 table             P  -
! 14 typcr             P  -
!  5 wft               P  -
!  7 wtt               P  -
!-----------------------------------------------------------------------
! Subprogram calls:
! NAME    DESCRIPTION
! csintg  Cross Section INTeGration of tables
! csperi  Cross Sections computation of PERImeter
! cspslt  Cross Section Preissmann SLoT
! cssect  Cross Section SECTional parameters
! cszwfz  Cross Section z Wf(z) dz
!=======================================================================
!
!
!***********************************************************************
! CVS log information:
!
! $Id$
!
! History:
! $Log: cstabl.pf,v $
! Revision 1.8  1999/03/15  15:49:10  kuipe_j
! tabs removed
!
! Revision 1.7  1997/09/30  09:23:01  kuipe_j
! density term improved for Preisman slot
!
! Revision 1.6  1997/06/04  11:18:07  kuipe_j
! Initialize arrays
!
! Revision 1.5  1997/01/23  08:28:48  kuipe_j
! Make flow module robust
!
! Revision 1.4  1996/05/30  09:59:55  kuipe_j
! comment char
!
! Revision 1.3  1995/05/30  09:54:26  hoeks_a
! Minor changes
!
! Revision 1.2  1995/05/30  06:55:32  hoeks_a
! files changed from dos-file to unix-files
!
! Revision 1.1  1995/04/13  06:58:35  hoeks_a
! Initial check-in
!
! Revision 1.2  1993/11/26  15:29:56  kuipe_j
! Update after finishing Sobeksel.
!
! Revision 1.1.1.1  1993/07/21  14:43:41  kuipe_j
! Initial version
!
!
!***********************************************************************
!
!     Include sobek constants
!
   include '..\include\sobcon.i'
   include '..\include\sobdim.i'
!
!     Declaration of Parameters:
!
   integer ngrid, maxlev, nbran, maxtab, ntabm, juer, ker
!
   integer branch(4,nbran),&
   &typcr(nbran)   ,&
   &nlev(ngrid)    ,&
   &bfrict(3,nbran),&
   &ntab(4,maxtab)
!
   real    wft (ngrid,maxlev) , aft  (ngrid,maxlev),&
   &wtt (ngrid,maxlev) , att  (ngrid,maxlev),&
   &of  (ngrid,maxlev) , izwft(ngrid,maxlev),&
   &sectc(ngrid,3)     , sectv(ngrid,dmsecv),&
   &prslot(3,nbran)    , psltvr(7,ngrid)    ,&
   &bfricp(6,ngrid)    , engpar(9)          ,&
   &grsize(4,ngrid,*)  , table(ntabm)       ,&
   &ws    (ngrid)
!
   double precision hlev(ngrid,maxlev)
!
   logical lsalt, lsedt
!
!     External function
!
   real      FLBOTT
!
!     Local variables
!
   integer ibr, i
!
!     Computation of Af-table from Wf-table
!     [ Doc. S-FO-001.5KV / Eq. 4-1 ]
!
   call CSINTG (ngrid, maxlev, nlev, hlev, wft, aft)
!
!     Computation of At-table from Wt-table
!     [ Doc. S-FO-001.5KV / Eq. [-] ]
!
   call CSINTG (ngrid, maxlev, nlev, hlev, wtt, att)
!
!     Computation of Of-table from Wf-table
!     [ Doc. S-FO-001.5KV / Eq. [-] ]
!     Of = wetted perimeter
!
   call CSPERI (ngrid, maxlev, nlev, hlev, wft, of)
!
!     Compute flow areas and wetted perimeters for main section
!     and subsection 1.
!
   call CSSECT (ngrid      ,nbran      ,branch     ,typcr      ,&
   &maxlev     ,nlev       ,hlev       ,wft        ,&
!                                          <subsec>    <secth0>
   &aft        ,of         ,sectc(1,1) ,sectv(1,2) ,&
!                  <secth1>    <wfh0>      <afh0>      <oh0>
   &sectv(1,3) ,sectc(1,2) ,sectv(1,4) ,sectv(1,6) ,&
!                  <wfh1>      <afh1>      <oh1>
   &sectc(1,3) ,sectv(1,5) ,sectv(1,7) ,psltvr     ,&
!                  <secths>
   &sectv(1,8) ,ws         ,lsedt      )
!
!     Compute table for integral [z * Wf(z)]
!     See coefficient A1m in d(rho)/dx term of momentum equation
!     [ Doc. S-FO-001.5KV / pg. 5-6 ]
!
   if ( lsalt ) then
      call CSZWFZ (ngrid  ,&
      &maxlev ,nlev   ,hlev   ,&
      &wft    ,izwft  )
   endif
!
!     Create a preissmann slot for branches with slot code = 1
!     Initialize for output purposes
!
   do 90 i=1,ngrid
      psltvr(5,i) = FLBOTT (i    ,ngrid  ,maxlev ,hlev)

90 continue
!
   do 100 ibr = 1, nbran
      if (int(prslot(1,ibr)) .eq. cslena) then
         call CSPSLT ( ibr    ,ngrid  ,nbran  ,branch ,&
         &prslot ,psltvr ,&
         &bfrict ,bfricp ,engpar ,grsize ,&
         &maxtab ,ntabm  ,ntab   ,table  ,&
         &maxlev ,nlev   ,hlev   ,&
         &wft    ,aft    ,wtt    ,att    ,&
         &of     ,juer   ,ker    )
      endif
100 continue
!
end
