rm -fv \
    libc-* \
    libc.* \
    libssh.so.* \
    libstdc++.so.* \
    libgcc.* \
    libuuid.so.* \
    libdl.so.* \
    libcurl.so.* \
    librt.so.* \
    libpthread.so.* \
    libm.so.* \
    libgcc_s.so.* \
    libz.so.* \
    libselinux.so.* \
    libbz2.so.* \
    libcom_err.so.* \
    libgssapi_krb5.so.* \
    libidn2.so.* \
    libk5crypto.so.* \
    libkeyutils.so.* \
    libkrb5.so.* \
    libkrb5support.so.* \
    liblzma.so.* \
    libnghttp2.so.* \
    libpcre2-8.so.* \
    libresolv.so.* \
    libsasl2.so.* \
    libsqlite3.so.* \
    libxml2.so.* \
    libzstd.so.* \
    libssl.so.* \
    libcrypt*