if(NOT TARGET test_delwaq_dimr)
    message(STATUS tests_unit_delwaq)
    add_subdirectory(${delwaq_unit_tests_module} tests_unit_delwaq)
    message(STATUS tests_integration_delwaq)
    add_subdirectory(${delwaq_integration_tests_module} tests_integration_delwaq)
    message(STATUS tests_utils_lgpl)
    add_subdirectory(${utils_lgpl_tests_module} tests_utils_lgpl)
endif()