#include "gtest/gtest.h"

#include "f90tw_defs_gtest.h"

#define HEADERLEVEL "gtest_level.h"
#define HEADERLEVELWHAT "implement_gtest_wrappers.h"
#define GTESTFUNCTION1 C_GTEST_LEVEL_CHECK1T1A
#define GTESTFUNCTION1M C_GTEST_LEVEL_CHECK1T1AM
#define GTESTFUNCTION2 C_GTEST_LEVEL_CHECK1T2A
#define GTESTFUNCTION2M C_GTEST_LEVEL_CHECK1T2AM
#define GTESTFUNCTION2STR C_GTEST_LEVEL_CHECK1T2STR
#define GTESTFUNCTION2STRM C_GTEST_LEVEL_CHECK1T2STRM
#define GTESTFUNCTION3 C_GTEST_LEVEL_CHECK1T3A
#define GTESTFUNCTION3M C_GTEST_LEVEL_CHECK1T3AM

#define DOINTERFACE
#include "gtest_what.h"
#undef DOINTERFACE

#undef GTESTFUNCTION3M
#undef GTESTFUNCTION3
#undef GTESTFUNCTION2STRM
#undef GTESTFUNCTION2STR
#undef GTESTFUNCTION2M
#undef GTESTFUNCTION2
#undef GTESTFUNCTION1M
#undef GTESTFUNCTION1
#undef HEADERLEVELWHAT
#undef HEADERLEVEL
