#ifdef F90TESTWRAPPERS

extern "C" {
#ifdef HAVECINT
        GTESTFUNCTION(LEVEL,WHAT,int,C_INT,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,int,C_INT,NAME1,NAME2)
#endif
#ifdef HAVECFLOAT
        GTESTFUNCTION(LEVEL,WHAT,float,C_FLOAT,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,float,C_FLOAT,NAME1,NAME2)
#endif
#ifdef HAVECDOUBLE
        GTESTFUNCTION(LEVEL,WHAT,double,C_DOUBLE,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,double,C_DOUBLE,NAME1,NAME2)
#endif
#ifdef HAVECBOOL
        GTESTFUNCTION(LEVEL,WHAT,bool,C_BOOL,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,bool,C_BOOL,NAME1,NAME2)
#endif
#ifdef DOSTR
        GTESTFUNCTION(LEVEL,WHAT,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,NAME1,NAME2)
#endif
}

#endif
