#ifdef F90TESTWRAPPERS
#define INTERFACENAME PREPENDF90( CONCAT2(LEVEL,WHAT,_))
#ifdef DOINTERFACE
#ifdef DOTESTS
!$f90tw TESTCODE(TEST, interface, INTERFACENAME, CONCAT2(TEST,INTERFACENAME,_),
!$f90tw   F90TWUSE (ISO_C_BINDING)
!$f90tw   F90TWUSE (assertions_gtest)
#endif
      interface INTERFACENAME
#endif

/* For each supported type the DOINTERFACE block includes the wrapper
// to the c function while the rest of the blocks set the corresponding
// utility functions implemented in the module. The HAVEDIM block set
// the same variants of the function with the 1D and 2D array argument(s)
// and. The HAVECAST block set the variants where instead of using the
// C_BOOL argument type, the default fortran logical type (kind=4) is
// used instead. Finally the DOTESTS block (located inside DOINTERFACE
// block) prepares simple tests for the implementation of f90tw using
// the directives approach. */
#ifdef HAVECINT
#ifdef DOINTERFACE
#ifdef DOTESTS
        !$f90tw F90TWSUB( INTERFACENAME, CINTARGS)
        !$f90tw F90TWSUB( INTERFACENAME, CINTARGS, "failed")
#ifdef HAVEDIM
        !$f90tw F90TWSUB( INTERFACENAME, CINT1DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, CINT1DARGS, "failed")
        !$f90tw F90TWSUB( INTERFACENAME, CINT2DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, CINT2DARGS, "failed")
#endif
#endif
        GTESTFUNCTION(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)
#endif
#ifdef HAVEDIM
        CONCAT(GTESTFUNCTION,DIM1)(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)

        CONCAT(GTESTFUNCTIONM,DIM1)(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)

        CONCAT(GTESTFUNCTION,DIM2)(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)

        CONCAT(GTESTFUNCTIONM,DIM2)(LEVEL,WHAT,integer,C_INT,NAME1,NAME2)
#endif
#endif

#ifdef HAVECFLOAT
#ifdef DOINTERFACE
#ifdef DOTESTS
        !$f90tw F90TWSUB( INTERFACENAME, CFLOATARGS)
        !$f90tw F90TWSUB( INTERFACENAME, CFLOATARGS, "failed")
#ifdef HAVEDIM
        !$f90tw F90TWSUB( INTERFACENAME, CFLOAT1DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, CFLOAT1DARGS, "failed")
        !$f90tw F90TWSUB( INTERFACENAME, CFLOAT2DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, CFLOAT2DARGS, "failed")
#endif
#endif
        GTESTFUNCTION(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)
#endif

#ifdef HAVEDIM
        CONCAT(GTESTFUNCTION,DIM1)(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)

        CONCAT(GTESTFUNCTIONM,DIM1)(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)

        CONCAT(GTESTFUNCTION,DIM2)(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)

        CONCAT(GTESTFUNCTIONM,DIM2)(LEVEL,WHAT,real,C_FLOAT,NAME1,NAME2)
#endif
#endif

#ifdef HAVECDOUBLE
#ifdef DOINTERFACE
#ifdef DOTESTS
        !$f90tw F90TWSUB( INTERFACENAME, CDOUBLEARGS)
        !$f90tw F90TWSUB( INTERFACENAME, CDOUBLEARGS, "failed")
#ifdef HAVEDIM
        !$f90tw F90TWSUB( INTERFACENAME, CDOUBLE1DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, CDOUBLE1DARGS, "failed")
        !$f90tw F90TWSUB( INTERFACENAME, CDOUBLE2DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, CDOUBLE2DARGS, "failed")
#endif
#endif
        GTESTFUNCTION(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)
#endif

#ifdef HAVEDIM
        CONCAT(GTESTFUNCTION,DIM1)(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)

        CONCAT(GTESTFUNCTIONM,DIM1)(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)

        CONCAT(GTESTFUNCTION,DIM2)(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)

        CONCAT(GTESTFUNCTIONM,DIM2)(LEVEL,WHAT,real,C_DOUBLE,NAME1,NAME2)
#endif
#endif

#ifdef HAVECBOOL
#ifdef DOINTERFACE
#ifdef DOTESTS
        !$f90tw F90TWSUB( INTERFACENAME, CBOOLARGS)
        !$f90tw F90TWSUB( INTERFACENAME, CBOOLARGS, "failed")
#ifdef HAVEDIM
        !$f90tw F90TWSUB( INTERFACENAME, CBOOL1DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, CBOOL1DARGS, "failed")
        !$f90tw F90TWSUB( INTERFACENAME, CBOOL2DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, CBOOL2DARGS, "failed")
#endif
#ifdef HAVECAST
        !$f90tw F90TWSUB( INTERFACENAME, LOGICALARGS)
        !$f90tw F90TWSUB( INTERFACENAME, LOGICALARGS, "failed")
#ifdef HAVEDIM
        !$f90tw F90TWSUB( INTERFACENAME, LOGICAL1DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, LOGICAL1DARGS, "failed")
        !$f90tw F90TWSUB( INTERFACENAME, LOGICAL2DARGS )
        !$f90tw F90TWSUB( INTERFACENAME, LOGICAL2DARGS, "failed")
#endif
#endif
#endif
        GTESTFUNCTION(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)
#endif

#ifdef HAVECAST
        CONCAT2(GTESTFUNCTION,CAST,_)(LEVEL,WHAT,LOGICAL,C_BOOL,NAME1,NAME2)

        CONCAT2(GTESTFUNCTIONM,CAST,_)(LEVEL,WHAT,LOGICAL,C_BOOL,NAME1,NAME2)

#ifdef HAVEDIM
        CONCAT2( CONCAT(GTESTFUNCTION,DIM1), CAST, _)(LEVEL,WHAT,LOGICAL,C_BOOL,NAME1,NAME2)

        CONCAT2( CONCAT(GTESTFUNCTIONM,DIM1), CAST, _)(LEVEL,WHAT,LOGICAL,C_BOOL,NAME1,NAME2)

        CONCAT2( CONCAT(GTESTFUNCTION,DIM2), CAST, _)(LEVEL,WHAT,LOGICAL,C_BOOL,NAME1,NAME2)

        CONCAT2( CONCAT(GTESTFUNCTIONM,DIM2), CAST, _)(LEVEL,WHAT,LOGICAL,C_BOOL,NAME1,NAME2)
#endif
#endif

#ifdef HAVEDIM
        CONCAT(GTESTFUNCTION,DIM1)(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)

        CONCAT(GTESTFUNCTIONM,DIM1)(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)

        CONCAT(GTESTFUNCTION,DIM2)(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)

        CONCAT(GTESTFUNCTIONM,DIM2)(LEVEL,WHAT,logical,C_BOOL,NAME1,NAME2)
#endif
#endif

#ifdef DOSTR
#ifdef DOINTERFACE
#ifdef DOTESTS
        !$f90tw F90TWSUB( INTERFACENAME, CSTRARGS)
        !$f90tw F90TWSUB( INTERFACENAME, CSTRARGS, "failed")
#endif
        GTESTFUNCTION(LEVEL,WHAT,NAME1,NAME2)

        GTESTFUNCTIONM(LEVEL,WHAT,NAME1,NAME2)
#endif
#endif

#ifdef DOINTERFACE
#ifdef DOTESTS
!$f90tw )
#endif
      end interface INTERFACENAME
#endif

#undef INTERFACENAME
#endif